### ISSUE TITLE
Linux Connection Sharing does not work

### ISSUE THREAD

**Issue by xSetBack** [evilsocket/pwnagotchi#1002]
I have downloaded the bash script directly from the repo, i have changed the interfaces names properly, but i get every time the same error:

Temporary failure resolving '[url]'.

My host laptop: Debian10 64bit

**Comment by slabua** [comment]
If all the rest is correctly configured, you might just have to set /etc/resolv.conf to something valid.

**Comment by xSetBack** [comment]
> If all the rest is correctly configured, you might just have to set /etc/resolv.conf to something valid.

I've solved using this script https://linux-pwnagotchi-conn-share.sourceforge.io/ that seems the original bash script for connection sharing with some modification made by https://t.me/xNigredo
