### ISSUE TITLE
handshakes stored in inaccessible folder

### ISSUE THREAD

**Issue by bwanaaa** [evilsocket/pwnagotchi#1006]
**Describe the bug**
1)cannot access handshakes directory
2)cannot copy handshakes to host machine

**To Reproduce**
1)
ssh into pwnagotchi
```
$ cd /root
-bash: cd: /root: Permission denied
```

2)
from a windows command prompt type:
```
pscp pi@10.0.0.2:/root/handshakes/ \Users\me
pi@10.0.0.2's password:
unable to identify /root/handshakes/: permission denied
```
I cannot copy handshakes to host machine

**Environment (please complete the following information):**
1.5.5
Win 10 Pro

**Additional context**

**Comment by codeleger** [comment]
You need to access it via root.

See:
`pi@pwnagotchi:~ $ cd /root/handshakes
-bash: cd: /root/handshakes: Permission denied
pi@pwnagotchi:~ $ su
Password:
root@pwnagotchi:/home/pi# cd /root/handshakes/
root@pwnagotchi:~/handshakes#`

**Comment by bwanaaa** [comment]
using pwnagotchi 1.5.3 (because 1.5.5 wont go into AI mode)
stock image flashed and booted
tried with the default password raspberry
```
 $su
Password:
su: Authentication failure
pi@pwnagotchi:~ $ su
Password:
su: Authentication failure
```

then changed password to something else
```
$passwd
Changing password for pi.
Current password:
New password:
Retype new password:
passwd: password updated successfully
pi@pwnagotchi:~ $ su
Password:
su: Authentication failure
```

and this is with windows terminal started in admin mode

**Comment by bwanaaa** [comment]
Duh....

`$sudo su`


works

**Comment by codeleger** [comment]
Yeah sorry, changed my root password. Therefore  su worked.
