### ISSUE TITLE
organize documentation

### ISSUE THREAD

**Issue by evilsocket** [evilsocket/pwnagotchi#101]
organize the documentation in the docs folder as markdown files that can also be used for the wiki

related to #50

**Comment by evilsocket** [comment]
derek: assign @hexwaxwing

**Comment by evilsocket** [comment]
derek assign: @hexwaxwing

**Comment by evilsocket** [comment]
Derek assign: hexwaxwing

**Comment by hexwaxwing** [comment]
Derek assign: hexwaxwing

**Comment by evilsocket** [comment]
docs moved to http://pwnagotchi.ai (repo https://github.com/evilsocket/www.pwnagotchi.ai)
