### ISSUE TITLE
Unable to ssh and perform basic pwnagotchi functions

### ISSUE THREAD

**Issue by Decapitater** [evilsocket/pwnagotchi#1018]
Hi,
I'm unable to ssh and perform basic functionalities such as bettercap login 
i created the config.toml file with Bluetooth+initial configs however after the first boot there were no changes to location of config file it was also not deleted and there is no folder named pwnagotchi in /etc/pwnagotchi/config.toml and so file is also missing there 
my machines recognises it as ethernet and i have changed the ip , netmask , gateway to required ones 
i can ping both 10.0.0.1 and 10.0.0.2 but the ssh is not working for 0.2 and showing wrong password for 0.1 
i have tried 2 different linux systems and 3 different cables all with power+data 
once when i tried i was able to enter bettercap but through 10.0.0.2 in browser and not using pwnagotchi.local 
I tried the host sharing script and the script always indicates the file exist

**Comment by gili-gili** [comment]
Hummmm,i think you can reinstall the system.It might work.

**Comment by Decapitater** [comment]
i tried 5 times with 2 different os no success i tried to use rpi imager too

**Comment by gili-gili** [comment]
What does your computer recognize your pi?If there's nothing wrong with the driver,it should be recognize like this
![QQ截图20210723135743](https://user-images.githubusercontent.com/53759426/126743256-53900f2b-d41c-4aa9-9d77-fca03fcf759b.png)
And then set up it.
![QQ截图20210723140643](https://user-images.githubusercontent.com/53759426/126744144-f08c94fd-2a57-4eb3-bae0-f69729acb4f4.png)
Then you should connect to your pi
![QQ截图20210723142006](https://user-images.githubusercontent.com/53759426/126744287-5642708c-c5f0-4f24-9dbb-3cb23f544e69.png)

**Comment by Decapitater** [comment]
sorry forgot to tell im on linux
its recognised as usb ethernet after 10.0.0.1 and mask procedure 
however i cannot access ssh i can ping both domains 10.0.0.1 and 10.0.0.2
the bettercap sits on 10.0.0.1

**Comment by gili-gili** [comment]
So you may have installed the wrong driver automatically.Unfortunately i only have Windows driver:(
Why not try Windows?
Another possibility is that you have written the wrong config.toml.

**Comment by Decapitater** [comment]
hmm any ideas on config.toml i tried many different ways to tackle it 
everytime the results were unique and sometimes they were straightup non functional 
i will try it with windows 
so would it work on my linux machine afterwards i wonder
thanks

**Comment by gili-gili** [comment]
You can follow
[https://pwnagotchi.ai/configuration/](url)
to configure it
And you probably need this driver
[https://drive.google.com/file/d/1UNy60lKIh7it-3gqsMJXutUkSxwebzKj/view?usp=sharing](url)
Or your pi W will be recognized like this
![QQ截图20210723192430](https://user-images.githubusercontent.com/53759426/126775276-3c40104f-4ff5-4cc2-8c59-e4bffee62cb0.png)

**Comment by Decapitater** [comment]
thanks

**Comment by Decapitater** [comment]
@evilsocket  somehelp needed

**Comment by Sundancer989** [comment]
Have you tried adding a blank ssh txt file to the boot partition to enable
ssh on first boot? Can you run nmap on the two IPs to confirm if the port
is open and still 22 or whatever it may have been changed to?

**Comment by Decapitater** [comment]
to confirm there is a ssh file that is blank. I haven't checked it with nmap.

**Comment by Decapitater** [comment]
Interesting finding 
I'm was able to ssh and make a working pwnagotchi with help of windows.
It seems to me that the linux working is not so great as i was unable to ssh on a linux comp even after making everything sure.
The build is now working.
Thanks @gili-gili  and @Sundancer989  for support

**Comment by WudUpA** [comment]
What did you use for the default password after 
ssh pi@10.0.0.2
The default password should be raspberry....right?
