### ISSUE TITLE
[Feature Request] Waveshare UPS Hat (C) plugin

### ISSUE THREAD

**Issue by Waffelo** [evilsocket/pwnagotchi#1068]
It would be cool if someone with more skills could make a plugin for Waveshare UPS Hat that would display battery capacity and status (charging/discharging, voltage). I tried to make it by myself but I am too new to pyhton and I failed..

https://www.waveshare.com/product/ups-hat-c.htm

**Comment by hannadiamond** [comment]
@Waffelo I just finished creating one! https://github.com/hannadiamond/pwnagotchi-plugins

**Comment by makerph** [comment]
@hannadiamond tested it and works great. thanks

**Comment by Waffelo** [comment]
@hannadiamond It seems to be working for me! I thank you so much! :D

**Comment by ch4istO** [comment]
hello, i am using the software:
https://github.com/DrSchottky/pwnagotchi/releases/tag/v1.5.6-beta2
I have the UPS_HAT C overlay, I copied the plugin and added it to config.toml but I can't activate it, how to solve the problem?

**Comment by do-ki** [comment]
have you enable i2c?

**Comment by ch4istO** [comment]
> have you enable i2c?

yes, but i solved the problem by installing pwnagotchi 1.5.5_WS V3 Patched, everything works in this software.
