### ISSUE TITLE
Add mobile home screen icon / browser favicon for web UI

### ISSUE THREAD

**Issue by andypiper** [evilsocket/pwnagotchi#1084]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
When opening the web UI (pwnagotchi.local:8080) in a browser tab, there is no favicon. When the page is added to a mobile homescreen (e.g. if you want to use it tethered to BT on iOS) it has a thumbnail, rather than a nice (o_o) style icon. Ideally, we could add a small image to improve both of these issues.

**Comment by therocco** [comment]
This was fixed in 1084 for anyone currently looking through issues for something to fix.
