### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by ArkAngeL43** [evilsocket/pwnagotchi#1107]
What algorithm does the AI use to learn?

**Comment by evilsocket** [comment]
Deep Reinforcement Learning Advantage Actor Critic

**Comment by evilsocket** [comment]
learn more on https://www.evilsocket.net/2019/10/19/Weaponizing-and-Gamifying-AI-for-WiFi-Hacking-Presenting-Pwnagotchi-1-0-0/
