### ISSUE TITLE
[BUG] create_sibling crash when using single cpu vm.

### ISSUE THREAD

**Issue by tisboyo** [evilsocket/pwnagotchi#112]
**Describe the bug**
Running Ubuntu 18.10 in a VirtualBox VM with a single cpu causes an error in create_sibling.sh on line 208. Changing the line to taskset -c 0 from taskset -c 1 allows the script to continue running. 

**To Reproduce**
1. ... Run Ubuntu in VM with single CPU
2. ... Run create_sibling.sh

**Expected behavior**
Expect script to finish build.

**Screenshots**

**Environment (please complete the following information):**
 - Pwnagotchi version - commit 58edfd2
 - OS version - Ubuntu 18.10 in VM
 - Type of hardware 
 - Any additional hardware used

**Additional context**
I did not test changing the VM to 2 CPU's, but I imagine that would also be a viable fix.

**Comment by dadav** [comment]
Thanks for your report! We are currently working on a replacement and won't put any further effort into maintaining this script. Please use the - soon to be availaible - installation method ^.^

**Comment by dadav** [comment]
Derek close
