### ISSUE TITLE
When is the Next Release

### ISSUE THREAD

**Issue by HeliusMagnum** [evilsocket/pwnagotchi#1124]
The last release was in  Apr 18, 2021. When will the next release be? Is the project dead?
https://github.com/evilsocket/pwnagotchi/releases/tag/v1.5.5

**Comment by wpa-3** [comment]
Sadly @evilsocket has stopped working on the project so its up to the community for now.

**Comment by BirbEXE** [comment]
https://twitter.com/birbexecutable/status/1535155492997042176

semi-official statement from the man himself
