### ISSUE TITLE
No display and No start with Waveshare V4

### ISSUE THREAD

**Issue by nickba86** [evilsocket/pwnagotchi#1187]
Hello Everyone!!
I hope you are doing well

**Describe the bug**
The screen does not show Anything.
The: "systemctl status pwnagotchi" Shows:
![image](https://github.com/evilsocket/pwnagotchi/assets/60796947/eb9392e6-426b-4051-8b7e-45996846cb7a)

The Log Shows:
![image](https://github.com/evilsocket/pwnagotchi/assets/60796947/aa602edc-0343-4a63-9573-8b9fc0415e57)

**To Reproduce**
1.  Make a Fresh copy of the pwnagotchi ISO in a SD card.
2. ... Connect to the pwnagotchi with FTP and replace the files with the last version on github
![image](https://github.com/evilsocket/pwnagotchi/assets/60796947/e7200ffc-afcb-43cc-9ad3-9c766062445b)
That's because the image available to download does have the latest changes with the support for the last type of screen 
4. Modify the CONFIG.TOML with:
ui.display.type = "waveshare213inb_v4" 
I understand that's the way to it because in the init we have the last modification:
![image](https://github.com/evilsocket/pwnagotchi/assets/60796947/b8f1aa44-066f-4ec7-bc36-f921d1a1d82f)

**Expected behavior**
I want to see the screen working with image.

**Environment (please complete the following information):**
 - Pwnagotchi version: Last image available: [v1.5.5](https://github.com/evilsocket/pwnagotchi/releases/tag/v1.5.5) 
 - Type of hardware: [Raspberry Pi Zero W](https://www.raspberrypi.org/products/raspberry-pi-zero-w/) and Waveshare 2.13 Inch e-Paper Display HAT V4 250x122 Resolution E-Ink Screen Electronic Paper Module with Embedded Controller Partial Refresh for Raspberry Pi/Jetson Nano/Arduino,Support SPI Interface

Thank you very much!!!!!

**Comment by Necr0byte** [comment]
Out of curiosity, can you try running `journalctl -u pwnagotchi.service` when you start it to see if it's writing anything to stderr before crashing?

**Comment by spitecho** [comment]
I had the same issue. I think it's because the most recent image (version 1.5.5, released April 18, 2021) doesn't have the Waveshare v4 update (released January 18, 2023).

I fixed it by copying the git cloned pwnagotchi folder and binary file from this repo:

```
ssh pi@10.0.0.2
sudo systemctl stop pwnagotchi.service
git clone https://github.com/evilsocket/pwnagotchi.git
cd pwnagotchi
sudo mv /etc/pwnagotchi /etc/pwnagotchi.bak
sudo cp -r pwnagotchi /etc/pwnagotchi
sudo mv /usr/local/bin/pwnagotchi /usr/local/bin/pwnagotchi.bak
sudo cp bin/pwnagotchi /usr/local/bin/pwnagotchi
```

Then I edited the /boot/config.toml to have 'ui.display.type = "waveshare213inb_v4"' and rebooted. This brought the screen up, but with flashing. Then I edited the /etc/pwnagotchi/config.toml to:
```
ui.display.type = "waveshare_3"
ui.fps = 0.5
```

Setting it to "waveshare_3" (despite the screen being labeled v4) removes the constant screen flashing and everything works as expected.

**Comment by nickba86** [comment]
Hi all !!! Thanks for the answer!! I am still facing issues:
@Necr0byte , the log does not says much:
![image](https://github.com/evilsocket/pwnagotchi/assets/60796947/78330bd3-19ab-4c72-9df5-8c6fadf94a52)

@spitecho , I am really sorry but I am afraid I was able to follow your instructions. Please help me to understand what I'm doing wrong:
1. "Then I edited the /boot/config.toml to have 'ui.display.type = "waveshare213inb_v4""
I was not able to find the config.toml in the boot
![image](https://github.com/evilsocket/pwnagotchi/assets/60796947/242394b2-a582-4f80-8542-874953b257ad)
As you can see in the image there no config.toml in boot.

2./etc/pwnagotchi/config.toml  
In this case I was able to modify but I am confuse because I understood there I should put 'ui.display.type = "waveshare213inb_v4"'

3.  In this path I put the last version:/usr/local/src/pwnagotchi
![image](https://github.com/evilsocket/pwnagotchi/assets/60796947/cf33d49e-a39c-4c9a-a54b-4be477a71d1c)

4. I did not know why doing this:
sudo mv /etc/pwnagotchi /etc/pwnagotchi.bak
sudo cp -r pwnagotchi /etc/pwnagotchi

It like putting the files in folder with the config???


Thank you very much for the help!!!!!!!!!

**Comment by spitecho** [comment]
You create the /boot/config.toml yourself and add the configuration lines to it. The lines are read at next boot, saved to /etc/pwnagotchi/config.toml, after which, the /boot/config.toml file is removed.

As for the rest, you're basically replacing one file (/usr/local/bin/pwnagotchi) and one folder (/etc/pwnagotchi/) with the updated versions from this project's main page.

**Comment by LookaD** [comment]
hi @spitecho im also having the same issue, i have a question about your method,
i installed with the image found in the release, so i dont have all the files inside of  the pwnagotchi that are in the updated repo,
so im not sure its working correctly.

i mean the image doesnt have all the .py files etc..

**Comment by spitecho** [comment]
@LookaD @nickba86 My mistake, I misremembered the location to copy the repo files to. Instead of "/etc/" the pwnagotchi folder from this repo should be copied to "/usr/local/lib/python3.7/dist-packages/".

**Comment by LookaD** [comment]
@spitecho ok so i did as you said, but i suppose im still missing something doing journalctl -u pwnagotchi.service is giving these errors

so i mean,
updating the pwnagotchi folder in  "/usr/local/lib/python3.7/dist-packages/"
and the file in /usr/local/bin/

i also did chmod 755 to make it as same as the original and chown for root:root

![immagine](https://github.com/evilsocket/pwnagotchi/assets/44865909/64cbaa02-abde-4db7-9c43-ac5189ada699)

Thank you for helping btw!

**Comment by nickba86** [comment]
Thank you very much @spitecho.
In order to make it work I had to follow your instructions. I will recap for others:
1. Update the  pwnagotchi after clone the image 1.5.5
2.  Follow the Guerilla Guide: https://github.com/Xyl0se/Pwnagotchi-new-guerilla-guide
3. Update the code: /usr/local/lib/python3.7/dist-packages/" (With the code in Github the last image does not have the last version).
![image](https://github.com/evilsocket/pwnagotchi/assets/60796947/fe6c8a9b-3e21-4399-9f83-38d34080bb6d)
![image](https://github.com/evilsocket/pwnagotchi/assets/60796947/911c3339-57d6-443d-80b8-cb6a9d4e5a8c)
4. Make a config.toml and put in the boot
![image](https://github.com/evilsocket/pwnagotchi/assets/60796947/c6384d4a-a091-4c17-b9d6-35699251e0f3)
In this case you must put
![image](https://github.com/evilsocket/pwnagotchi/assets/60796947/acc7f466-91e4-49de-aff8-e256edb07f3e)
5. In /etc/pwnagotchi  you put the other config.toml
![image](https://github.com/evilsocket/pwnagotchi/assets/60796947/fc48b4ed-589d-4504-b699-14b6d01bbe72)
in this case you must put: ui.display.type = "waveshare_3" in the config.toml
6. Enjoy


THANKS!!!!!!!! :) 👍
