### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by gtrdlr** [evilsocket/pwnagotchi#122]
**Describe the bug**
The URL:
https://github.com/evilsocket/pwnagotchi/blob/master/docs/install.md —

Refers to a pre-compiled release file, however the destination lacks any release files. Monitoring GitHub today, there have been a bunch of updates, which likely explains why it hasn’t made sense to drop a release, but figured it was worth mentioning here. LOVE the project thus far and especially the community involvement. 

**To Reproduce**
1. ...
2. ...
3. ...

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - Pwnagotchi version
 - OS version
 - Type of hardware
 - Any additional hardware used

**Additional context**

**Comment by evilsocket** [comment]
yes because it's work in progress, it's not a bug
