### ISSUE TITLE
Help with Root access

### ISSUE THREAD

**Issue by lordpysc** [evilsocket/pwnagotchi#1235]
Ive been trying to install the custom plugins using FileZilla, already did the PermitRootLoging yes and changed the passwd root. But FileZIlla says cannot connect. 
I tried also 10.0.0.2:8080 but when I type Username: root Password: password it asks for it again and again.
Thanks in advance.

<img width="512" alt="Screenshot 2024-06-16 134950" src="https://github.com/evilsocket/pwnagotchi/assets/145384942/68dcb65b-aaf3-476b-bef0-4d5c3e55fbce">
<img width="590" alt="Screenshot 2024-06-16 135052" src="https://github.com/evilsocket/pwnagotchi/assets/145384942/a963f077-c534-4209-a9bc-9be9cbbcd86c">
<img width="957" alt="Screenshot 2024-06-16 135126" src="https://github.com/evilsocket/pwnagotchi/assets/145384942/26952371-3ad8-4c87-8868-81418c9ae0fa">

**Comment by timmosaurusrex** [comment]
Hi there. You need to remove the # before #PermitRootLogin yes. Then you need to restart the ssh service or reboot the system. 
And for the web ui. The default login is username: changeme password: changeme

**Comment by lordpysc** [comment]
> Hi there. You need to remove the # before #PermitRootLogin yes. Then you need to restart the ssh service or reboot the system. And for the web ui. The default login is username: changeme password: changeme

Thanks Timmosaurusrex, I'm checking it now. Appreciate your time and support.

**Comment by lordpysc** [comment]
Can I bother you with another question? 

If you can help me understand whats going on with the bluetooth tether, i tried with my android phone and while connected to the pc, i was able to pair it, and it connected to my phone. Used the webui 192.168.44.44 and everything worked, but fun thing was after changing ports, from data to power, phone didnt connect and i switch to data and no luck, actually my pwnagotchi disappeared from my phone's Bluetooth devices....
