### ISSUE TITLE
The install guide references ready-built images that doesn't exist

### ISSUE THREAD

**Issue by swedishmike** [evilsocket/pwnagotchi#130]
In the install guide here: https://github.com/evilsocket/pwnagotchi/blob/master/docs/install.md there's a reference to downloading the latest images from the release page.

Looking at https://github.com/evilsocket/pwnagotchi/releases there are no files available for download.

I'm not sure if that is due to the files being too large to upload to GitHub or if there's any other reason but should this be removed from the install guide for now?

In case there's agreement to removing it - please let me know and I can try and get a PR in which instead updates the install.md to use the create_sibling.sh to generate the image etc.

**Comment by evilsocket** [comment]
the reason is because there's no stable release yet.
