### ISSUE TITLE
[BUG] Round / truncate times in UI

### ISSUE THREAD

**Issue by deveth0** [evilsocket/pwnagotchi#137]
**Describe the bug**
When the pwnagotchi is sleeping, it displays the remaining time. The time is not rounded or truncated, so it might be something like `(13.9999999999s)` which is too long to display. 

**To Reproduce**
1. Run a pwnagotchi
2. Wait for it to sleep
3. Check the time

**Expected behavior**
I'd expect that the remaining time is displayed as a integer and not a float.

**Environment (please complete the following information):**
 - Pwnagotchi version: build 5968030ed
 - OS version: create_sibling.sh created raspbian
 - Type of hardware: Pi0W with waveshare v1

**Comment by evilsocket** [comment]
fixed already

**Comment by deveth0** [comment]
kwl, thx
