### ISSUE TITLE
Add multi-display preview

### ISSUE THREAD

**Issue by dadav** [evilsocket/pwnagotchi#149]
For the translation process it would be awesome to see all possible displays at the same time without starting multiple preview.py's.

idea from @caquino

**Comment by dadav** [comment]
Derek add label: idea

**Comment by evilsocket** [comment]
maybe the preview.py script can be just changed to, optionally, just generate pngs of every state? or maybe just one png with all of them?

**Comment by dadav** [comment]
> maybe the preview.py script can be just changed to, optionally, just generate pngs of every state? or maybe just one png with all of them?

Yeah, sure! I would prefer one picture with all of them^^
