### ISSUE TITLE
Reset display once in a while

### ISSUE THREAD

**Issue by deveth0** [evilsocket/pwnagotchi#156]
**Is your feature request related to a problem? Please describe.**
When running for some time, the eink display gets very noisy due to partial updates. It would be nice, if the display could be completely wiped once in a while look crispy again

**Describe the solution you'd like**
I'd suggest to have a configuration which allows to set the time in minutes after which the display is cleared.

**Comment by dadav** [comment]
Derek close

screen_refresh plugin got added.

**Comment by deveth0** [comment]
Thx!
