### ISSUE TITLE
Update screen while AI is initialising

### ISSUE THREAD

**Issue by dipsylala** [evilsocket/pwnagotchi#182]
This relates to a one-off issue when a Pwnagtochi is initialising - there is a significant delay while the AI is built

Is there the opportunity to update the screen with something appropriate while this occurs? This would give feedback to users who don't have it plugged into HDMI. or SSH

Something like:

(∩⌣̀_⌣́) Collecting my thoughts

...just to show that things are happening.

**Comment by evilsocket** [comment]
a lot of things happen in 30 minutes, so it doesn't make sense to just stick to one face to indicate the AI is loading ... in order to understand the transitions between modes, you can read this https://pwnagotchi.ai/usage/#auto-ai-and-manu-modes
