### ISSUE TITLE
[BUG] releases page empty

### ISSUE THREAD

**Issue by bitwave** [evilsocket/pwnagotchi#185]
The releases page on github doesn't show any download links...

Regards,
bitwave

**Comment by damianchoc** [comment]
pls fix this

**Comment by caquino** [comment]
This is not a bug, we don't have any releases yet.

**Comment by damianchoc** [comment]
> This is not a bug, we don't have any releases yet.

so how make a image to burn to sd card?

**Comment by bitwave** [comment]
Oh, because I read the docs and saw the link to the releases page. I'm not able to run packer under Arch Linux to generate the image using the arm-image plugin and qemu...

**Comment by caquino** [comment]
That's not supported or working yet, we will announce when it's available.

**Comment by bitwave** [comment]
Where can we get working images to test it?
