### ISSUE TITLE
Feature? White list Wifi networks/networks to ignore

### ISSUE THREAD

**Issue by gh0stshell** [evilsocket/pwnagotchi#225]
When i was using Wifi Pineapples this was a feature so it would ignore my network while looking and watching all others. Is this option available? If not, anyone think this may be helpful?

**Comment by Mila432** [comment]
https://github.com/evilsocket/pwnagotchi/blob/master/pwnagotchi/defaults.yml#L66

**Comment by gh0stshell** [comment]
Thanks! could not find that in the docs
