### ISSUE TITLE
[BUG] Text overlap on busy screen

### ISSUE THREAD

**Issue by dipsylala** [evilsocket/pwnagotchi#229]
The text can sometimes overlap when particular statuses occur:

![pwnagotchi](https://user-images.githubusercontent.com/6720159/66439156-ae926f80-ea26-11e9-891b-8a8ac360f268.png)

Potential changes?
Move the unit name to the top centre of the display, above the top bar. This is a slightly smaller area for the name, but it's a fixed width (assuming max APS detected are 999). This would allow the name to be truncated with '...' if it exceeds 14 characters (based on current font width). An alternative location would be above the face but crowding that area means the face doesn't stand out as much.

Moving the unit name lets the feedback area grow upwards a line, which should make overlap with the friends bar less likely - it would be able to handle 4 lines without clashing. More space might be gained by making the line spacing less, at the cost of readability.

![image](https://user-images.githubusercontent.com/6720159/66439837-dbe01d00-ea28-11e9-984c-3827ef904f8f.png)

**Comment by caquino** [comment]
@dipsylala which display are you using?

**Comment by dipsylala** [comment]
I knew there was something I missed! InkyPhat, so 212x104.
I'm assuming UI testing's been on the 250x122 WS2, but the Slack channel has a lot of people mentioning the InkyPhat so maybe it needs to be considered too?

Could the UI assume 4 lines maximum for the Info area and use a combination of font scaling/line spacing to get it to fit depending on screen size?

**Comment by evilsocket** [comment]
or maybe (as suggested by @hexwaxwing) the name could be on top of the face?

**Comment by dipsylala** [comment]
I wasn't sure whether that might make it too crowded around the face - couple of mockups below. Shifting the name left and the text up certainly seems the quickest to implement.

WS2:
![image](https://user-images.githubusercontent.com/6720159/66479482-817ca600-ea94-11e9-8e42-2e01c762c0b1.png)

Inkyphat:
![image](https://user-images.githubusercontent.com/6720159/66479457-76297a80-ea94-11e9-8656-f84412a23c0e.png)

**Comment by evilsocket** [comment]
i've tested on a waveshare v1, anybody can pull and test the fix for inky and papirus too?

**Comment by dipsylala** [comment]
Looks great on inky - thanks!

![image](https://user-images.githubusercontent.com/6720159/66483278-ac6af800-ea9c-11e9-9963-47b8b10e8498.png)

**Comment by evilsocket** [comment]
👍

**Comment by jonspraggins** [comment]
Similar issue.  When using PiSugar2 plugin and bt-tether, there's some crowding.  No option to hide bt-tether (but keep enabled) from what I can tell.
![Screenshot from 2021-02-04 22-12-24](https://user-images.githubusercontent.com/1907993/106984723-1dc0c680-6736-11eb-9418-f928bae9cdd3.png)
