### ISSUE TITLE
Idea for Plugins name

### ISSUE THREAD

**Issue by gh0stshell** [evilsocket/pwnagotchi#242]
Like how other devices such as the Wifi Pineapple calls there plugins infusions to have it unique to that device. Maybe instead of using the good old Plugins for Pwnagotchi, maybe Skills?

**Comment by evilsocket** [comment]
i can't understand a single thing, and it looks a duplicate of #105 anyway.

**Comment by gh0stshell** [comment]
Its quite simple, instead of using the generic name "Plugin", maybe customize it a bit and make it unique to pwnagotchi, i suggested "Skills". The idea is based of other devices like the Wifi Pineapple that call their extra packages something other then the common "Plugin" name.
