### ISSUE TITLE
[BUG] pwnagotchi says channel is free when it's actually full

### ISSUE THREAD

**Issue by wxcafe** [evilsocket/pwnagotchi#257]
**Describe the bug**
pwnagotch says channel 11 is empty, but channel 11 is actually quite full

**To Reproduce**
Let the pwnagotchi run for ~13h I guess? No input

**Expected behavior**
Not get notices that a channel that's full is empty

**Screenshots**
![image](https://user-images.githubusercontent.com/3009327/66666938-cf71e500-ec1f-11e9-88fc-2a2f0cdeb19c.png)

**Environment (please complete the following information):**
 - Pwnagotchi version: 1.0.0RC2
 - OS version: whatever's in 1.0.0RC2
 - Type of hardware: Pi Zero W with the waveshare hat
 - Any additional hardware used: none

**Comment by evilsocket** [comment]
that was a legacy feature, disabling it now, thanks for the report 👍
