### ISSUE TITLE
[BUG] Tweepy 3.6 is incompatible with python 3.7

### ISSUE THREAD

**Issue by dadav** [evilsocket/pwnagotchi#258]
**Describe the bug**
Tweepy 3.6.0 doesnt support python 3.7.

**To Reproduce**
python3 -c 'import tweepy'

**Expected behavior**
Import is working

**Screenshots**
-

**Environment (please complete the following information):**
 - RC2

**Additional context**
Version 3.7.0 fixes the problem.

**Comment by dadav** [comment]
Problem is: They use the async keyword as a variable name >.>

**Comment by evilsocket** [comment]
uhm?
![Schermata 2019-10-11 alle 19 25 44](https://user-images.githubusercontent.com/86922/66671714-f0a4f680-ec5c-11e9-817f-355f345c976b.png)

**Comment by dadav** [comment]
hooowww??
Bug is definetly in 3.6.0:
https://github.com/tweepy/tweepy/blob/v3.6.0/tweepy/streaming.py#L358

It got fixed here: https://github.com/tweepy/tweepy/pull/1042
which is available in 3.7.0

gonna investigate!

**Comment by dadav** [comment]
hm, maybe i upgraded the package while compiling the package on the pi somehow^^ Problem doesnt seem to occure to other ppl.
