### ISSUE TITLE
[BUG] v1.0.0RC2 Image Kernel Panic

### ISSUE THREAD

**Issue by gaterbyte** [evilsocket/pwnagotchi#262]
**Describe the bug**
v1.0.0RC2 Image Flash Results in a Kernel Panic

**To Reproduce**
1. Download image file
2. use Etcher to flash
3. insert micro sdcard into pi and power on

**Expected behavior**
When Reverting back to "pwnagotchi-raspbian-lite-master.img" pi boots normally.

**Screenshots**
![IMG_20191011_141821_DRO(1)_copy](https://user-images.githubusercontent.com/5060500/66686492-7fe9e400-ec34-11e9-942a-2e468bfe0df7.jpg)

**Environment (please complete the following information):**
 - pwnagotchi-raspbian-lite-v1.0.0RC2
 - Pi 0 W
 - 32GB Pny SD card, inateck usb/ethernet hub, mini-hdmi to monitor

**Comment by evilsocket** [comment]
does the release SHA256 match with your zip?

**Comment by gaterbyte** [comment]
cd498ed144f464068dcab6f7648460803df242baa8a0f940054094035ffcfb52  
pwnagotchi-raspbian-lite-v1.0.0RC2.zip

f8d6ad92a4d0d0760850330379d1254c9e4d2ba8f4841d2563b1032ab4eb505b  
pwnagotchi-raspbian-lite-v1.0.0RC2.img

Which are different from what you posted... Let me try to re-download and report back.

**Comment by gaterbyte** [comment]
Pull via wget verses chrome download, and sha256 now matches.
Checking install and running now.
