### ISSUE TITLE
document first boot key generation times

### ISSUE THREAD

**Issue by evilsocket** [evilsocket/pwnagotchi#268]
document first boot key generation times, the fact that the unit needs to generate rsa keys at first boot so it might take a couple of minutes to get online. This process should not be interrupted in order for the keys not to be corrupted.

**Comment by evilsocket** [comment]
cc @hexwaxwing

**Comment by hexwaxwing** [comment]
done https://github.com/evilsocket/www.pwnagotchi.ai/pull/23
