### ISSUE TITLE
Improve Inky pHAT refresh

### ISSUE THREAD

**Issue by neurovish** [evilsocket/pwnagotchi#272]
Issue: 
The Inky pHAT display refresh is absurd. By default, it is optimized for a color display with minima ghosting. Using the b&w mode instead of color mode is an improvement, but still leaves room for improivement.

Proposed solution: 
Update the timings in the Inky e-Ink Display Driver, /usr/local/lib/python3.7/dist-packages/inky/inky.py. The display behaviour is defined via lookup tables starting at line 95 of inky.py. I modified these lines to remove the initial "all black" flash and reduced the time for the cleared display during the transitions. 

Testing:
Updated on the Inky unit I have. Tested with just removing the initial screen flash, which greatly improved the refresh rate, but still had a lot of lag between transitions. Reduced the screen clearing time next and have been running for the past day with no issues. Still much slower than the waveshare, but acceptable with little/no ghosting.

Thoughts:
Modifying the Inky driver directly is not an elegant fix and will likely be overwritten by an update and the lines are likely to change, so I wouldn't trust a patch reliably working between releases. I've also only tested with black and white mode, so the color mode is still likely slow or not improvable without ghosting.

**Comment by zenzen666** [comment]
The default values for inkyphat are unusable for an application like pwnagotchi. 
I've tried the neurovish's changes and they works pretty well fixing the annoying _inkyphat doom's refresh_
