### ISSUE TITLE
default.yml or defaults.yml ?

### ISSUE THREAD

**Issue by b0bje** [evilsocket/pwnagotchi#280]
image contains default.yml, yet all the docs reference a defaults.yml

just wondering if that was done on purpose ? or just a typo.

Anyway, loving the project :)

**Comment by incredincomp** [comment]
Hey @b0bje , where in the Docs are you seeing `defaults.yml`? Is it the doc stuff on this repo or the pwnagotchi.ai site and where? Thank you!

**Comment by evilsocket** [comment]
there are defaults.yml (the one bundled with the app) and /etc/pwnagotchi/default.yml, copied at first run.

**Comment by evilsocket** [comment]
@incredincomp the PR you sent had a dead link, please check your modifications before sending PRs.
