### ISSUE TITLE
Re-implement disabling RPI 0W LED

### ISSUE THREAD

**Issue by charagarlnad** [evilsocket/pwnagotchi#283]
**Describe the solution you'd like**

A simple config option to enable to disable onboard LED lights for a tiny power savings, as default behavior is to keep it enabled to signify the unit is powered. Could be extendable so other boards could be detected and have their LEDs disabled as well.

**Additional context**

[Here](https://github.com/charagarlnad/pwnagotchi/blob/65e4fd7db3d342410c4d3fecb7fd562b5844ae60/pwnagotchi/plugins/default/disable_led.py) is how I would go about it, however there may be a better way to implement it.

**Comment by evilsocket** [comment]
The led is used on boot to indicate activity.
