### ISSUE TITLE
Implement ui for Waveshare Oled Hat

### ISSUE THREAD

**Issue by systemik** [evilsocket/pwnagotchi#291]
Implement Waveshare Oled Hat (https://www.waveshare.com/wiki/1.3inch_OLED_HAT)
Need to refactor view.py to have more variables to handle different screens

Need to be tested by the community

**Comment by systemik** [comment]
Code is ready. Just need to clean-up and to a PR.

**Comment by evilsocket** [comment]
merged and did some basic refactoring, tested on Waveshare v2 too
