### ISSUE TITLE
Probable typo: default.yml or defaultS.yml

### ISSUE THREAD

**Issue by drego85** [evilsocket/pwnagotchi#300]
**Describe the bug**

Inside the code or in the description we refer to the pwnagotchi/default.yml or pwnagotchi/default**s**.yml. 

Example in:  pwnagotchi/builder/pwnagotchi.yml I find:

```
All the configuration options can be found on /etc/pwnagotchi/default**s**.yml
```

or

```
Add your configuration overrides on this file any configuration changes done to default**s**.yml will be lost!
```

but actually the file is in:  /etc/pwnagotchi/default.yml

I din't modify the pwnagotchi/builder/pwnagotchi.yml file myself because I saw that there are references to default**s**.yml also in: pwnagotchi/utils.py or setup.py and I didn't want to create any other errors.

I prefer that you look at us, you know the project better than me.

**Environment (please complete the following information):**
 - v1.0.0RC4

**Comment by evilsocket** [comment]
fixed, thanks
