### ISSUE TITLE
[BUG] backup.sh script need zip package for create system backup

### ISSUE THREAD

**Issue by javitu** [evilsocket/pwnagotchi#301]
**Describe the bug**
backup.sh script use zip program for create system backup but isn't included

**To Reproduce**
1. Run /usr/local/src/pwnagotchi/scripts/backup.sh
2. Error "-bash: zip: command not found"

**Environment (please complete the following information):**
 - v1.0.0 RC4
 - Raspberry Pi Zero W

**Comment by evilsocket** [comment]
no it doesn't, backup script is supposed to be run on the host computer, not the unit.
