### ISSUE TITLE
missing timestamp in .net-pos.json + .geo.json

### ISSUE THREAD

**Issue by xenDE** [evilsocket/pwnagotchi#308]
the saved .net-pos.json and generated .geo.json missed the timestamp:

{"wifiAccessPoints": [{"macAddress": "a0:64:8f:41:12:a8", "signalStrength": -71}, {"macAddress": "04:f0:21:41:80:c8", "signalStrength": -71}, {"macAddress": "34:31:c4:f2:07:c6", "
signalStrength": -72}, {"macAddress": "62:e3:27:24:55:aa", "signalStrength": -73}, {"macAddress": "52:28:6d:5a:9d:f9", "signalStrength": -75}, {"macAddress": "04:f0:21:15:ea:cd",
"signalStrength": -76}]}

would be nice, if the timestamp can be added like in the gps plugin created json file.

**Comment by dadav** [comment]
Derek assign: dadav

**Comment by xenDE** [comment]
timestamps added in all position .json files
