### ISSUE TITLE
[BUG] _reboot() doesn't work

### ISSUE THREAD

**Issue by wy4h5evs4eve4s** [evilsocket/pwnagotchi#313]
**Describe the bug**
The `_reboot(self)` method of the agent calls:
```
        os.system("/usr/bin/sync")
        os.system("/usr/sbin/shutdown -r now")
```
On my pwnagotchi 1.0.0RC4 these binaries do not exist, but I have `/bin/sync` and `/sbin/shutdown` instead.

As a result, automatic reboot after N epochs of inactivity just doesn't work.

**To Reproduce**
1. Install 1.0.0RC4 on a RPi0
2. Leave it running untile the nexmon blindness bug kicks in
3. The log will eventually say:
```
[CRITICAL] 10 epochs without visible access points -> rebooting 
[WARNING] writing recovery data to /root/.pwnagotchi-recovery 
[WARNING] rebooting the system ...
```
4. Nothing happens

**Expected behavior**
I'd expect the proper commands to get called and the board to reboot.

**Environment (please complete the following information):**
 - Pwnagotchi version: 1.0.0RC4
 - OS version: pwnagotchi release image v1.0.0RC4
 - Type of hardware: RPi0

**Comment by dadav** [comment]
Maybe we just use this?
https://github.com/evilsocket/pwnagotchi/blob/e15d0f33239c4f4b3ec58a813e53fd9f767b345c/pwnagotchi/__init__.py#L60
