### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by FerdinandoPH** [evilsocket/pwnagotchi#340]
1. Does the pwnagotchi work with a Raspberry Pi 4B?
2. Does the pwnagotchi work with WPA2?
3. Is there any way for transforming the eaten handshakes of the pwnagotchi into Wifi keys?

Could someone answer me these questions? I think that pwnagotchi is an amazing project!

**Comment by zerocolTHS** [comment]
1. I think so
2. Yes of course 
3. There is an option to upload them online for cracking or you could copy them to your pc and crack them yourself. 

Good luck.
