### ISSUE TITLE
Stable Baselines Project Page

### ISSUE THREAD

**Issue by araffin** [evilsocket/pwnagotchi#342]
Hello,

Now that pwnagotchi has reached the 1.0 milestones, we would appreciate if you could do a PR to add it to the project page of stable-baselines: https://stable-baselines.readthedocs.io/en/master/misc/projects.html

Please don't forget to update the changelog if you do so.

Cheers.

**Comment by evilsocket** [comment]
👍 https://github.com/hill-a/stable-baselines/pull/515
