### ISSUE TITLE
SSH_OPTION Variable

### ISSUE THREAD

**Issue by acbekoac** [evilsocket/pwnagotchi#353]
I am missing an inital empty Varaible SSH_OPTIONS Variable, that is used with scp in the for loop

    SSH_OPTION=""
    ...
    scp ${SSH_OPTIONS) -Cr root@...

After "ssh-copy-id -i /path/to/public.key" and setting this Variable to "-i /path/to/private.key" you do not have to enter the  password during backup process anymore

**Comment by dadav** [comment]
is there a reason you don't use a ssh-agent?

**Comment by dadav** [comment]
One month passed...no reponse.

Derek close

**Comment by dadav** [comment]
Derek close
