### ISSUE TITLE
Move Scripts or Make symlink to scripts in /etc/pwnagotchi?

### ISSUE THREAD

**Issue by gh0stshell** [evilsocket/pwnagotchi#357]
**Is your feature request related to a problem? Please describe.**
It would be much easier to have needed items under /etc/pwnagotchi like scripts, docs say to use scripts/backup, but not many knew it was under /usr/local/src/pwnagotchi/scripts

**Describe the solution you'd like**
Move scripts to /etc/pwnagotchi or make a symlink to scripts location in /etc/pwnagotchi

**Comment by evilsocket** [comment]
that's very against the posix standard.
