### ISSUE TITLE
Name Selector on Firstboot

### ISSUE THREAD

**Issue by mlinton** [evilsocket/pwnagotchi#363]
It would seem that a good idea would be to set the hostname of each unit randomly on first boot as part of the initialization (like the key material).  This would provide some variety within PwnGrid as well as part of people's own customization.

We could preload the image with the following files:
- https://github.com/danielmiessler/SecLists/tree/master/Usernames/Names

And then do a selection of given and family name from the lists (this might be too westernized a method?)

Then take the two names and concatenate them together to set the hostname in the config.yml file which also makes adjustments to the /etc/hosts /etc/hostname and /etc/motd files.

**Comment by evilsocket** [comment]
very westernized ...

**Comment by evilsocket** [comment]
i mean, i like the idea, but i don't think those lists would work ...
