### ISSUE TITLE
Multi device support for bt-tethering

### ISSUE THREAD

**Issue by maxxer** [evilsocket/pwnagotchi#379]
It would be great to be able to configure multiple devices for BT tethering.
When polling for a BT device it should loop through all the configured ones and connect the first available.

All devices should have the *mac, ip, netmask, share_internet* options, so one can have different config for each (consider tethering on either android or iphone).

**Comment by dadav** [comment]
Derek assign: dadav

**Comment by evilsocket** [comment]
closed with https://github.com/evilsocket/pwnagotchi/pull/492
