### ISSUE TITLE
Can't rotate 2.7 waveshare screen image

### ISSUE THREAD

**Issue by talonawd91** [evilsocket/pwnagotchi#390]
Trying to use the "rotation" statement within config.yml setting the display to "rotation: 180". This has no effect on the image. 

**To Reproduce**
Change display section in config.yml:
ui:
   fps: 0.0
   display:
      type: 'waveshare27inch'
      color: 'black'
      rotation: 180

**Expected behavior**
screen should rotate 180 from current orientation. 

**Environment (please complete the following information):**
 - Pwnagotchi version:
(v1.1.0b)
 - OS version
10.1
 - Type of hardware
Pi 3b+
 - Any additional hardware used
No

**Comment by dadav** [comment]
180 is the default value. Maybe try to set it to something different like 90. Still no rotation?

**Comment by Frituurpanda** [comment]
@dadav @talonawd91 almost correct, ```rotation: 0``` will do the trick ;).

**Comment by dadav** [comment]
@talonawd91 can you confirm? :)

**Comment by talonawd91** [comment]
I just changed it. Works like a charm. Thanks for the guidance.
