### ISSUE TITLE
[BUG] backup.sh includes defaults.yml which causes issues after upgrades

### ISSUE THREAD

**Issue by deveth0** [evilsocket/pwnagotchi#396]
**Describe the bug**
The `backup.sh` script currently also includes `defaults.yml`. This can result in missing config values when updating your device. 

**To Reproduce**
1. run `backup.sh`
2. upgrade your device
3. restore backup
4. check `defaults.yml`

**Expected behavior**
`defaults.yml` should be excluded from backup as the user should not change anything here. Another (probably better option) would be to not use `/etc/pwnagotchi/defaults.yml` but `/usr/local/lib/python3.7/dist-packages/pwnagotchi/defaults.yml` and remove this problem completely.

**Comment by evilsocket** [comment]
in the new release the defaults.yml just gets overwritten if it's different from the package one
