### ISSUE TITLE
Possible logic error in /plugins/default/AircrackOnly.py

### ISSUE THREAD

**Issue by eth0hex** [evilsocket/pwnagotchi#398]
Lines 32 and 40 are misspelt. As it is, AFAIK, it'll never delete a bad capture file.
note: I don't actually have a Pwnagotchi, just wanted to point out what I thought was an obvious spelling mistake

**Comment by dadav** [comment]
Yep, you are right!

**Comment by dadav** [comment]
Derek add label: Bug

**Comment by eth0hex** [comment]
Yee, first time on github BTW. Is it alright if I refactor the code too? It kinda hurts to look at NGL
