### ISSUE TITLE
twitter.py

### ISSUE THREAD

**Issue by PeterAlfonsLoch** [evilsocket/pwnagotchi#405]
if i knew thw iaaue i could name it. what i did was i got the keys, i then thether over bluetooth. so appearantly need manual mode so i try manual mode and all i get is:
![image](https://user-images.githubusercontent.com/2743562/67619576-af384d80-f7fd-11e9-9493-9b216b668c3e.png)

**Comment by dadav** [comment]
`pip3 install --upgrade tweepy==3.7.0`

**Comment by PeterAlfonsLoch** [comment]
works thx
