### ISSUE TITLE
On 1.1.0 RC0 fresh install hosts and hostname are both set to "pwnagotchi" no matter what you place as your name in the config.yml

### ISSUE THREAD

**Issue by Arttumiro** [evilsocket/pwnagotchi#406]
I dont know if it matters too much since it is simple to change it but still, i didnt try manually rebooting and seeing if that changed things.

**Comment by Arttumiro** [comment]
There is the log file
[pwnagotchi.log](https://github.com/evilsocket/pwnagotchi/files/3774967/pwnagotchi.log)

**Comment by evilsocket** [comment]
from this log i can see your unit's hostname is `Kattichu` ... what's the issue?

**Comment by Arttumiro** [comment]
I changed that manually, i thought that making "name: 'kattichu' " in the config.yml would change it automatically, either way im just being dumb.

**Comment by evilsocket** [comment]
i needed the logs before you changed it manually, the very first boot ...

**Comment by 234v244** [comment]
I have a similar problem, and don't know how to fix it.
