### ISSUE TITLE
Version 1.0.1RC0 up timer and rpi3 on manual mode after shutdown

### ISSUE THREAD

**Issue by Arttumiro** [evilsocket/pwnagotchi#407]
Used sudo shutdown now, unplugged and plugged the rpi3 back in to power, it went into manual and the up time is all bugged out
![Screenshot_20191026-170313~2](https://user-images.githubusercontent.com/24279100/67620774-07c61580-f813-11e9-886a-d9a62cfe1f36.png)

**Comment by Arttumiro** [comment]
Wait.. i mean version 1.1.0, sorry

**Comment by Arttumiro** [comment]
I got it into auto mode by doing the command that appears when you ssh into it, but always on power on its on manual when using a raspberry pi 3 atleast

**Comment by evilsocket** [comment]
weird, the uptime is read from  `/proc/uptime`, can you cat it when this happens and paste it here?

**Comment by Arttumiro** [comment]
Its still going to manual mode but the uptime bug is not happening anymore
