### ISSUE TITLE
A way to delete inactive pwnagotchis? Like my old kattichu now

### ISSUE THREAD

**Issue by Arttumiro** [evilsocket/pwnagotchi#410]
My old kattichu was https://pwnagotchi.ai/pwnfile/#!519bade3c0c12794c9c324376cfd80855b6892ddd331b237de2bf02b3cb6f4a3
My new Kattichu is link https://pwnagotchi.ai/pwnfile/#!5020a6c3d7ede327567dcfddeee9e155bd96cf555581166a1baa58c84a7e37e6
If you could add a system for deleting/requesting deletion of old inactive units it would be cool
Its extra work though and i feel bad

**Comment by evilsocket** [comment]
no worries, i'll setup a cronjob server side for that, it's not a big deal 👍
