### ISSUE TITLE
[BUG] plugins/quickdic does not consider wordlists in subdirectories

### ISSUE THREAD

**Issue by coderobe** [evilsocket/pwnagotchi#418]
**Describe the bug**
quickdic does not consider wordlists in subdirectories of `wordlist_folder`

**To Reproduce**
1. Place wordlists in subdirectories of `wordlist_folder`
2. They will not be used

**Expected behavior**
Wordlists in subdirectories should be included, to allow for proper sorting of `wordlist_folder`

**Screenshots**
n/a

**Environment (please complete the following information):**
 - Pwnagotchi version: v1.1.0RC0

**Additional context**
n/a

**Comment by dadav** [comment]
This plugin is not supported anymore

**Comment by dadav** [comment]
Derek close
