### ISSUE TITLE
Sleeping Face for Pwnagotchi When Off

### ISSUE THREAD

**Issue by nikhiljha** [evilsocket/pwnagotchi#446]
**Describe the solution you'd like**
When shut down properly, draw some Zs and a face with closed eyes to indicate that the pwnagotchi is sleeping.

**Comment by evilsocket** [comment]
that's already the case https://github.com/evilsocket/pwnagotchi/blob/master/pwnagotchi/ui/view.py#L266

**Comment by dwi** [comment]
That is not working. Just turned off the Pwnagotchi in MANU mode via WebUI and the summary screen (Kicked/Friends/Got...) is on the display.

**Comment by evilsocket** [comment]
it appears to be a timing problem: there's a 5 seconds sleep before turning the unit off, which is enough on faster displays (waveshare v2) to display the Zzz message, but not on waveshare v1 and others.
