### ISSUE TITLE
[BUG] Always in MANU mode on Pi3

### ISSUE THREAD

**Issue by maxxer** [evilsocket/pwnagotchi#460]
**Describe the bug**
1.1.0RC0 on Pi3 always starts in MANU mode, despite of the ethernet cable being connected or not

**Expected behavior**
When ethernet cable is disconnected it should start in AUTO mode.

**Environment (please complete the following information):**
 - Pwnagotchi version: 1.1.0RC0
 - Type of hardware: Raspberry Pi3+

**Additional context**
A fix has been posted [on Reddit](https://www.reddit.com/r/pwnagotchi/comments/dnz5p2/pi3_always_boots_to_manu/f5j3up9/) and also [here](https://github.com/evilsocket/pwnagotchi/commit/a78a4b0b3e5cfbdfea481e140e6c02e0bdb1f72d#commitcomment-35683998)

**Comment by Nodeswitch** [comment]
Can be replicated on the Pi 4, also.

**Comment by maxxer** [comment]
Fix merged
