### ISSUE TITLE
Implement whitelist option for onlinehashcrack.com plugin

### ISSUE THREAD

**Issue by maxxer** [evilsocket/pwnagotchi#462]
**Is your feature request related to a problem? Please describe.**
It would be great to be able to *whitelist* some networks so that their handshake is not uploaded to onlinehashcrack.com

**Describe the solution you'd like**
A configuration option for the plugin, something like `whitelist` (for consistency with other plugins) or better `exclude`

**Comment by dadav** [comment]
Derek assign: dadav

**Comment by dadav** [comment]
Good idea, will do the same for web-sec

**Comment by dadav** [comment]
Derek close
