### ISSUE TITLE
home base WAP to update/upload/backup.

### ISSUE THREAD

**Issue by Shleeble** [evilsocket/pwnagotchi#467]
**Is your feature request related to a problem? Please describe.**
I'd love to be able to have a homebase WAP and when my little pwnie friend comes back home with me. notices it's near that WAP and connects to the internet to update/upload handshakes. then disconnects and goes back to doing it's thing.

**Describe the solution you'd like**
backup to s3 or scp would be cool too.

**Comment by dadav** [comment]
Dupplicate of #207

**Comment by dadav** [comment]
Derek close
