### ISSUE TITLE
auto-update should update launchers and service files too

### ISSUE THREAD

**Issue by evilsocket** [evilsocket/pwnagotchi#470]
Right now .service and launcher files are only updated if the full .img is reflashed as they're part of the builder. They should be migrated as assets of the python codebase that get installed from the setup.py during the `pip3 install .` update procedure.

**Comment by evilsocket** [comment]
@caquino setup.py doesn't seem to be executed while using pip3 install ., any idea what'd be a nice way to have those files updated from the auto-update plugin?

**Comment by evilsocket** [comment]
@dadav that'd be great, any ref?

**Comment by emedvedev** [comment]
Same probably goes for MOTD since it has a version number and links that could eventually change?

**Comment by dadav** [comment]
> Same probably goes for MOTD since it has a version number and links that could eventually change?

I would keep that in ansible and update the file in the auto-update plugin.

**Comment by evilsocket** [comment]
@dadav i just pushed the change be414e57b308565b47a40a76d92fbb1a4b5e426c but i'd need another couple of eyes to double check / review the code
