### ISSUE TITLE
Request adding support for the Waveshare 2.9 inch e-ink display

### ISSUE THREAD

**Issue by opteeks** [evilsocket/pwnagotchi#474]
**Is your feature request related to a problem? Please describe.**
No
**Describe the solution you'd like**
Add the drivers required to support the Waveshare 2.9 inch e-ink display by Waveshare
**Describe alternatives you've considered**

**Additional context**

**Comment by coderobe** [comment]
Should work (https://github.com/evilsocket/pwnagotchi/issues/360)

**Comment by opteeks** [comment]
I just submitted a PR to add the drivers for the 2.9 inch display. I've tested it thoroughly with my pi zero w and display and have the layout finalized.

**Comment by evilsocket** [comment]
@opteeks your PR has conflicts, i need you to fix them before i can merge

**Comment by opteeks** [comment]
Conflicts have been resolved.

**Comment by TheSidd** [comment]
@opteeks has this been resolved? What do I need to add in config to make it work?

**Comment by opteeks** [comment]
This was already resolved and has been working fine.
