### ISSUE TITLE
Configure USB Ethernet with a DHCP server

### ISSUE THREAD

**Issue by RoganDawes** [evilsocket/pwnagotchi#481]
**Is your feature request related to a problem? Please describe.**
Using Fedora, I have to reconfigure the IP address associated with the USB-Ethernet interface of my Pi Zero W, every time it reboots. Not sure why, but NetworkManager seems to forget the fixed IP address that I configure for it.

**Describe the solution you'd like**
It seems to me that a better option anyway would be to have the Pi Zero W act as a dhcp server, and assign an IP address to the Linux/Windows/OS X "host" when the interface is brought up, much like the P4wnP1 ALOA installation does. Then there should be even less requirement to fiddle with the network configuration.

**Describe alternatives you've considered**
Can't think of anything else better than the above suggestion, or at least not worse than the current state of affairs.

**Additional context**
N/A

**Comment by GideonWolfe** [comment]
Is this why I can't get a working SSH connection into my pi 0 with pwnagotchi? I can see the USB ethernet device but I can't get a valid IPv4 address for it

**Comment by RoganDawes** [comment]
Most likely. You need to assign a static IP address in the 10.0.0.0/24
range. I normally use 10.0.0.1, then you can ssh to 10.0.0.2.

**Comment by sayak-brm** [comment]
@GideonWolfe this may help you:

https://pwnagotchi.ai/configuration/#steps-to-complete-on-your-host-the-pc-that-you-are-connecting-the-pi-to

**Comment by sayak-brm** [comment]
@GideonWolfe [Steps to complete on your host](https://pwnagotchi.ai/configuration/#steps-to-complete-on-your-host-the-pc-that-you-are-connecting-the-pi-to)

**Comment by xBelladonna** [comment]
I have successfully implemented this with dnsmasq and BOOTP for stupid Windows clients that don't accept DHCPOFFER without dhcp option 3 set.... anyway, now to figure out how to package it into the image builder 😬

**Comment by dadav** [comment]
Derek close
