### ISSUE TITLE
Don't overwrite usb0-cfg on update

### ISSUE THREAD

**Issue by deveth0** [evilsocket/pwnagotchi#484]
**Is your feature request related to a problem? Please describe.**
When using the auto-update plugin on a pwnagotchi unit with a changed ip, the ip is reset to the default. 
I've got multiple devices with a unique ip each, so I cannot use the default. 

**Describe the solution you'd like**
The update should only update the actual application related stuff and not the ip configuration. 
Another option would be a blacklist where you can add files to ignore.

**Comment by deveth0** [comment]
Oh sry

**Comment by evilsocket** [comment]
👍
