### ISSUE TITLE
[BUG] backup.sh fails if the unit has never connected to the grid

### ISSUE THREAD

**Issue by Shleeble** [evilsocket/pwnagotchi#497]
**Describe the bug**
fails with missing file. `tar: /root/.api-report.json: Cannot stat: No such file or directory`

**To Reproduce**
standard usage 
```
backup.sh Calvin Calvin.zip

tar: /root/.api-report.json: Cannot stat: No such file or directory
tar: Exiting with failure status due to previous errors
```

**Screenshots**

**Environment (please complete the following information):**
 - Pwnagotchi version 1.1.1
 - Type of hardware standard zero

**Comment by danielhoherd** [comment]
An identical failure scenario under different circumstances is the absence of `/var/log/pwnagotchi*.gz` files

```
/var/log/pwnagotchi.log
tar: /var/log/pwnagotchi*.gz: Cannot stat: No such file or directory
/home/pi/.bashrc
tar: Exiting with failure status due to previous errors
```
