### ISSUE TITLE
document / explain the reward function

### ISSUE THREAD

**Issue by evilsocket** [evilsocket/pwnagotchi#50]
the reward function should be documented and explained clearly so people can understand exactly what they need to do in order for the AI to improve :D

**Comment by incredincomp** [comment]
Whats your opinion on a Wiki page for this project on git here? Could start with copying some portions of the readme over, and then figure out where to go from there. 
### Home
Something something.
### Pwnagotchi Reward Documentation
Something something.
### Plugin Development
Something something.
###  Troubleshooting & Common Errors
Something something.
