### ISSUE TITLE
[Enhancement] send null PIN and/or PIXIE wps to vulnerable routers in order to retrieve PSK.

### ISSUE THREAD

**Issue by hackabean** [evilsocket/pwnagotchi#511]
Any chance to expand on pawnagotchi abilities to include: 

1) null PIN attack: https://github.com/derv82/wifite2/issues/40 many routers up there are still vulnerable.
2) inluclude PIXIE wps as one of its features to obtain PSK.

Thanks for all the work.

With regards
HB.

**Comment by evilsocket** [comment]
duplicate of #457
