### ISSUE TITLE
UPS_LITE display info not clearing[BUG]

### ISSUE THREAD

**Issue by miotislucifugis** [evilsocket/pwnagotchi#521]
**Describe the bug**
I just received and installed my ups.lite and am finding that the battery info at the top of the screen is not clearing... new characters are drawn on top of the old ones.  This is happening on both the waveshare screen and on the web ui.    A reboot clears things (obviously) but just until the data/numbers change.    The percentage part seems to be working properly... it appears to be the bold UPS text and the voltage that are affected.

**edit: actually just realizing that is just overlapping with bluetooth connection status data.... Any lack of clearing old characters might just be an artifact of that... explains why the 2nd half of the ups data (bat%) is working fine.   Can there be some options for what data is displayed?  since space is kinda limited up there, i could live w/o voltage and just have the battery level.   

Also... not sure if you are aware,  ups_lite is no longer listed in the plugin section of default.yml.      Enabling it in config.yml  still seems to work tho, aside from the old characters overlapping    (meaning it doenst crash when booting... )  

Using rpi0W,  pwnagotchi v1.1.1. , w/ Waveshare v2  & usp-lite,

**Comment by dwi** [comment]
Workaround: I solved this by removing the voltage from the information and shifting the indicator to the right. You can do the following changes in the usp lite plugin 

`def on_ui_setup(ui):
    ui.add_element('ups', LabeledValue(color=BLACK, label='UPS', value='0%/0V', position=(ui.width() / 2 + 15, 0),
                                       label_font=fonts.Bold, text_font=fonts.Medium))`


`def on_ui_update(ui):
    ui.set('ups', "%2i%%" % (ups.capacity()))`

**Comment by evilsocket** [comment]
can i have a screenshot so i can understand what we're talking about?

**Comment by miotislucifugis** [comment]
Sorry, my original post is a little unclear. basically the BT plugin and the UPS plugin are writing to the same place on the screen.    DWi's workaround solved it.  here is an image:


![IMG_4243](https://user-images.githubusercontent.com/20709580/68252583-e7a50c00-fff3-11e9-8d99-8e4a6f51baba.JPG)

**Comment by spectrophagus** [comment]
Just another vote for this issue... can confirm the @dwi workaround fits nicely between BT status and uptime.

**Comment by evilsocket** [comment]
I need a screeshot of the new layout

**Comment by dwi** [comment]
This is how it looks with the change applied

![](https://i.imgur.com/N4qvPaH.png)
