### ISSUE TITLE
led blinking plugin

### ISSUE THREAD

**Issue by evilsocket** [evilsocket/pwnagotchi#522]
For people without a display, it'd be nice to have a plugin that will blink the led with specific patterns depending on the callback. The patterns should be configurable.

**Comment by mrseeker** [comment]
You can flash the LED's by sending a command to it:
https://www.jeffgeerling.com/blogs/jeff-geerling/controlling-pwr-act-leds-raspberry-pi

I would also recommend that the patterns are done in morse, easy to understand for the less advanced. (https://en.wikipedia.org/wiki/Morse_code)

**Comment by evilsocket** [comment]
yep https://github.com/evilsocket/pwnagotchi/blob/master/builder/data/usr/bin/pwnlib#L4
