### ISSUE TITLE
[BUG] webui zoom doesn't respect aspect ratio

### ISSUE THREAD

**Issue by evilsocket** [evilsocket/pwnagotchi#523]
Given my noobiness in html and css, on some mobile devices the web ui is kind of crap in landscape mode, this is because the image width is just 100% and therefore its aspect ratio is taken into account instead of the display aspect ratio:

![image](https://user-images.githubusercontent.com/86922/68221001-0225b800-ffe9-11e9-8c4e-a0d224d0e3c5.png)
(notice the bottom part being not visible)

Ideally this should be fixed by something like https://stackoverflow.com/questions/42367898/css-image-full-screen-but-will-maintain-aspect-ratio

**Comment by deveth0** [comment]
```
<div style="height: 100vh; width: 100vw;">
        <img src="http://zelda.local:8080/ui?1572971976843" id="ui" style="height:100%; max-width:100vw; object-fit: contain;">
</div>
```

I currently don't have a running unit with the current development version, so I can only test it with 1.1.0.

**Comment by evilsocket** [comment]
it works!!!! :D

**Comment by evilsocket** [comment]
mmm it works on mobile ... but on desktop it takes full height, the picture is centered and buttons are not visible :/

**Comment by deveth0** [comment]
ahh damn it, sorry :(

**Comment by evilsocket** [comment]
no worries, we'll figure this out ... somehow ...

**Comment by deveth0** [comment]
We really need to find a designer :D I just fixed the image issue and added some basic rules for the layout. Furthermore I increased the size of the buttons, they still look awkward but at least it's now possible to touch the right one ;)

<img width="1502" alt="Screenshot 2019-11-05 at 23 19 49" src="https://user-images.githubusercontent.com/1718655/68251236-fc4cc880-0022-11ea-8e66-df99b2c4862b.png">

**Comment by deveth0** [comment]
PR: https://github.com/evilsocket/pwnagotchi/pull/535
hope this is ok now :)

**Comment by evilsocket** [comment]
![image](https://user-images.githubusercontent.com/86922/68291814-ebd03880-008a-11ea-896a-cfe814d0e9ee.png)

👍

**Comment by mrseeker** [comment]
I would love to see that face on a big giant screen...

**Comment by evilsocket** [comment]
![03F87099-560C-40D1-AE8C-5D9466934205](https://user-images.githubusercontent.com/86922/68298011-a581d600-0098-11ea-9275-bcb98fce943f.jpeg)

**Comment by deveth0** [comment]
muahaha :D probably the buttons should be displayed in a flyout menu? but the aspect ratio of image and screen does not match, so this would only help a bit.
