### ISSUE TITLE
No screen on RPi0 + USB wi-fi

### ISSUE THREAD

**Issue by zeroSocket** [evilsocket/pwnagotchi#524]
**Platform**
Rapsberry Pi 0 (not W)

**Mods**
USB-OTG disabled in config.txt (`dtoverlay=dwc2`) and cmdline.txt

**Peripherals**
- Keyboard
- TP-LINK TL-WN722N
- HDMI connected/disconnected
- Waveshare e-ink v2

**Behavior**
At pwnagotchi startup the e-ink display blink (suppose the init command), systemctl confirm that bettercap and pwnagotchi services are active, journalctl show pwnagotchi work correctly but no data appear on display. With and without HDMI connected.
The same display, with same config.yml work perfectly on RPi0W.
Any suggestions?

**Comment by evilsocket** [comment]
check this section and basically replace mon0 with what you have https://pwnagotchi.ai/installation/#installing-on-any-gnu-linux
