### ISSUE TITLE
implement log rotation

### ISSUE THREAD

**Issue by evilsocket** [evilsocket/pwnagotchi#527]
we should implement log rotation as /var/log/pwnagotchi.log can become huge over time ... we don't want to split session data, so we need to make sure to run the rotation at start when the new session is not started yet

**Comment by flow23** [comment]
Hi, I'm having a lot of issues with the log rotation for pwnagotchi.log
It breaks the system because it's full after a long session.

/var/log-> du -sh pwnagotchi*
0	pwnagotchi-2.gz
25G	pwnagotchi-2.log
58M	pwnagotchi.gz
8.0K	pwnagotchi.log
