### ISSUE TITLE
[feature] Force pwnagotchi to update

### ISSUE THREAD

**Issue by mrseeker** [evilsocket/pwnagotchi#528]
**Is your feature request related to a problem? Please describe.**
I have no clue when and if the pwnagotchi gets updated, especially when it's on auto-update mode. It tried to update at the same time I was on cellular, which means that it tried to download a huge file on a 128kb/s connection, and choked on my cellular data.

**Describe the solution you'd like**
I would love to force a manual update of the pwnagotchi, either by starting a script in MANU mode or forcing itself to update by pressing a button on it's website (port 8080).

**Describe alternatives you've considered**
Not using bluetooth network sharing when on cellular?

**Comment by evilsocket** [comment]
sudo rm -rf /root/.auto-update && sudo service pwnagotchi restart
