### ISSUE TITLE
Some displays do not display the memtemp data in the correct place [BUG]

### ISSUE THREAD

**Issue by ian-rubenstein-mpf** [evilsocket/pwnagotchi#532]
**Describe the bug**
The memtemp data is running over the edge of the screen

**To Reproduce**
1. load v1.2.1
2. enable memtemp (vertical or horizontal)
3. load UI

**Expected behavior**
Should be in the same location on screen as prior to update

**Screenshots**
![image (2)](https://user-images.githubusercontent.com/25467862/68246030-07cdce80-ffe6-11e9-8646-f1d4895ad014.png)

**Environment (please complete the following information):**
 - Pwnagotchi version 1.2.1
 - OS version osx, n/a
 - Type of hardware rpi0w, waveshare_213d
 - Any additional hardware used

**Additional context**

**Comment by Arttumiro** [comment]
According to RustyPaper on slack same happens with Inky too, once switched to waveshare_2 everything looks perfect

**Comment by srcr** [comment]
![ui](https://user-images.githubusercontent.com/1507320/68504840-3d80ea80-0266-11ea-94ca-b9d06f27869d.png)

**Environment**
Pwnagotchi version 1.2.1
Type of hardware rpi0w, inkyphat

**note**
Just my 2 cents just upgraded to 1.2.1, and found the issue as described.

**Comment by srcr** [comment]
<a href="https://github.com/evilsocket/pwnagotchi/issues/532" class="u-in-reply-to"></a>![ui](https://user-images.githubusercontent.com/1507320/68504840-3d80ea80-0266-11ea-94ca-b9d06f27869d.png)

**Environment**
Pwnagotchi version 1.2.1
Type of hardware rpi0w, inkyphat

**note**
Just my 2 cents just upgraded to 1.2.1, and found the issue as described.

**Comment by charlesrocket** [comment]
Same on `1.2.1` with inkyphat-red (rpi0w).

**Comment by charlesrocket** [comment]
@ian-rubenstein-mpf could you drop `213d` from the title since its not just for waveshare case?

**Comment by b33rANDfr13s** [comment]
memtemp was configured on my first 60+ hours or runtime in the last week.
![memtemp issue](https://user-images.githubusercontent.com/32944708/68537123-2822c380-032d-11ea-9db4-a57077161256.PNG)

I just configured auto-update today and updated to pwnagotchi v1.2.1

After updating, both horizontal and vertical memtemp displays are partially off-screen.

**Comment by charlesrocket** [comment]
btw this might be an offtop but i think you should also blank your device names?) https://github.com/evilsocket/pwnagotchi/blob/master/pwnagotchi/plugins/default/grid.py#L12-L41 in case your device found internet over somewhere and you forgot to turn off `grid`
