### ISSUE TITLE
Delete invalid net-pos files

### ISSUE THREAD

**Issue by deveth0** [evilsocket/pwnagotchi#533]
Currently the net-pos plugin adds file, which could not be parsed (due to network errors, invalid format or other things) to a  skiplist.

I don't think that it's worth to keep any file that could not be parsed in the handshakes folder, therefor I'd suggest to delete all files, which throw an error that is not network related.

**Comment by evilsocket** [comment]
i suggest instead that the plugin just doesn't create the files if no valid data is ready

**Comment by dadav** [comment]
Will fix that

**Comment by dadav** [comment]
Derek assign dadav
