### ISSUE TITLE
Whitelist not working [BUG]

### ISSUE THREAD

**Issue by elipsius** [evilsocket/pwnagotchi#540]
**Describe the bug**
Whitelist no matter how entered is not used, my SSID is still pwned.  

**To Reproduce**
1. Launch with whitelist enabled and provide SSID list
2. wait
3. It will start pwning the whitelisted SSIDs and pcap files will appear.

**Expected behavior**
Should not pwn whitelist SSIDs
Whitelisted SSID pcap files should not show up

**Environment (please complete the following information):**
 - Pwnagotchi version 1.1.1
 - pwnagotchi image download 1.1.1
 - Raspberry Pi 3+
 - Google WiFi mesh is being whitelisted

**Comment by Generic42** [comment]
I'm also seeing this behavior.

I've attempted the following white list formats
First attempt:

main:
  name: 'pwnagotchi'
  whitelist:
    - 'YourHomeNetworkMaybe'
    - 'Your  Second home Maybe'
  plugins:
    grid:
      enabled: true
      report: true
      exclude:
    - 'YourHomeNetworkMaybe'
    - 'Your  Second home Maybe'


Other attemp
main:
  name: 'pwnagotchi'
  whitelist:
    - YourHomeNetworkMaybe
    - Your  Second home Maybe
  plugins:
    grid:
      enabled: true
      report: true
      exclude:
    - YourHomeNetworkMaybe
    - Your  Second home Maybe

**Comment by nucow69** [comment]
I noticed that too. Then I saw that the FAQ on pwnagotchi.ai says:
Your access points handshakes get still captured. This only prevents the deauth of the clients.

**Comment by elipsius** [comment]
I'm doing this:

**Comment by dadav** [comment]
Guys, like @nucow69 this is an expected behaviour. The whitelisted APs won't get "pwned" aka. deauthed, but captured. This is not a bug.

**Comment by evilsocket** [comment]
As per docs:

**Your access points handshakes get still captured. This only prevents the deauth of the clients.**

**Comment by fennectech** [comment]
This should be mentioned on pwnagotchi.ai   Thank you for the info :3

**Comment by RussellTaylor83** [comment]
Adding this to the docs would make a lot of sense. I'll see if I can add it and get it past PR.

**Comment by funkymonkey5150** [comment]
It is mentioned on there
