### ISSUE TITLE
[BUG] Serial instead of Ethernet interface

### ISSUE THREAD

**Issue by happostroph** [evilsocket/pwnagotchi#543]
**Describe the bug**
On a fresh install of my pwnagotchi, I plugged it for the first time, but no new Ethernet interface appear.
With some investigations, I discover a serial USB (COM4 for me) that appear when I plug the rpi0.
Is it related to #159 ?

**To Reproduce**
1. Flash SD.
2. Create config.yml and edit it with the good properties.
3. Plug the SD crad to the RPI0.
4. Plug the RPI0 on Windows.

**Screenshot**

![Capture](https://user-images.githubusercontent.com/22621888/68347057-1c00f100-00f6-11ea-9d3a-52213ccf9286.PNG)
Here is the serial USB.

**Expected behavior**
I expect a new ethernet interface for my pownagotchi

**Environment:**
 - Pwnagotchi version : 1.2.1
 - OS version : Windows 10 1903
 - Type of hardware : RPI0WH + waveshare_2 + SD card SanDisk UHS-1
 - Any additional hardware used : mini usb - usb cable which allow data transfert

Thank you in advance !

**Comment by PeachMangoes** [comment]
here try this one.
just update then that serial port using the driver below.

got it from this [site](https://www.factoryforward.com/pi-zero-w-headless-setup-windows10-rndis-driver-issue-resolved/)

[mod-duo-rndis.zip](https://github.com/evilsocket/pwnagotchi/files/3817781/mod-duo-rndis.zip)

**Comment by mrseeker** [comment]
I had this same issue, fixed it by installing the RNDIS driver. Known bug, should be referenced here: https://pwnagotchi.ai/configuration/#connect-to-your-pwnagotchi

**Comment by happostroph** [comment]
Well thanks guys ! This works perfectly.
I followed the steps from your [site ](https://www.factoryforward.com/pi-zero-w-headless-setup-windows10-rndis-driver-issue-resolved/) @PeachMangoes 

Yes @mrseeker , this could help many new users

**Comment by hallo545401** [comment]
@PeachMangoes helped me as well, should really be mansioned on the config page
