### ISSUE TITLE
UI to show GPS info when enabled

### ISSUE THREAD

**Issue by elipsius** [evilsocket/pwnagotchi#544]
**Is your feature request related to a problem? Please describe.**
Not being able to easily tell if GPS is configured and receiving data.  

**Describe the solution you'd like**
It would be nice to have the UI display that GPS is enabled and provide basic GPS data, probably just lat and lon of current location.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by benleb** [comment]
https://github.com/evilsocket/pwnagotchi/pull/602 :)

**Comment by dadav** [comment]
Derek close
