### ISSUE TITLE
Improve clarity on restore

### ISSUE THREAD

**Issue by dalanmiller** [evilsocket/pwnagotchi#548]
> If you want to restore a backup instead, you can copy the contents of the /etc/pwnagotchi backupped folder in the FAT32 boot partition as /boot/pwnagotchi

I think this portion in the docs could be clarified a bit more.

Does this mean dump all the files we'd normally find in `/etc/pwnagotchi` into a new folder called `pwnagotchi` in the `/boot` folder we find when mounting the SD card?

**Comment by evilsocket** [comment]
yes ... it literally means that

**Comment by evilsocket** [comment]
( also the repo for the doc is https://github.com/evilsocket/www.pwnagotchi.ai )
