### ISSUE TITLE
Load user contributed plugin configuration yml files

### ISSUE THREAD

**Issue by tabbek** [evilsocket/pwnagotchi#552]
**Is your feature request related to a problem? Please describe.**
Mostly an ease of use enhancement

**Describe the solution you'd like**
A section in the config.yml and supporting code to load additional yml files for non-core plugins, rather than copy-pasting their contents back into config.yml.

**Describe alternatives you've considered**
With the recent update to remove some plugins from the core set (commit 2ea8e7f), it currently requires copy-pasting from the now external individual plugin yml files back into config.yml.
It would be convenient to have something like a 'contrib-plugins' section in core to enable/disable and provide a path to a directory to load additional yml files from, possibly the option to load all from directory, or specify specific files to load.

**Comment by evilsocket** [comment]
that would fragment the configuration just to avoid pasting it ... nope.
