### ISSUE TITLE
-S for the bmap-tool is not completely done

### ISSUE THREAD

**Issue by benleb** [evilsocket/pwnagotchi#56]
`./create_sibling.sh: illegal option -- S`

seems like the option is documented but not (fully) implemented. probably this was missed in https://github.com/evilsocket/pwnagotchi/pull/41 ?

**Comment by caquino** [comment]
cc @dadav is this something that we need to keep open for you to track?

**Comment by massar** [comment]
no need to use -S for sparse, as it detects the mode (well, it detects if bmaptool is available).

**Comment by benleb** [comment]
yes and this works like expected 👍 but if there is a -S option in the doc, the tool should recognize it 😅

**Comment by massar** [comment]
I'll submit a patch to remove it ;)

**Comment by caquino** [comment]
We are moving to a new builder where create_sibling will not be needed anymore, and because of that I'm closing this ticket.

Thanks for reporting the issue!

**Comment by caquino** [comment]
Derek close
