### ISSUE TITLE
[BUG] on WN722N

### ISSUE THREAD

**Issue by phr34k0** [evilsocket/pwnagotchi#568]
**Describe the bug**
Followed the installation guide on https://pwnagotchi.ai/installation/ and had it installed on Raspberry 2 using the latest release found in this Git, flashed onto an SDCard and booted. Had the interfaces changed in the config and whatnot. Everything works except getting it to work with an old single band 2.4ghz WN722N Atheros Adapter.

> [   40.602592] usb 1-1.3: new high-speed USB device number 5 using dwc2
> [   40.754432] usb 1-1.3: New USB device found, idVendor=0cf3, idProduct=9271, bcdDevice= 1.08
> [   40.754457] usb 1-1.3: New USB device strings: Mfr=16, Product=32, SerialNumber=48
> [   40.754471] usb 1-1.3: Product: USB2.0 WLAN
> [   40.754499] usb 1-1.3: Manufacturer: ATHEROS
> [   40.754511] usb 1-1.3: SerialNumber: 12345
> [   40.756143] usb 1-1.3: ath9k_htc: Firmware ath9k_htc/htc_9271-1.4.0.fw requested
> [   41.053573] usb 1-1.3: ath9k_htc: Transferred FW: ath9k_htc/htc_9271-1.4.0.fw, size: 51008
> [   42.072671] ath9k_htc 1-1.3:1.0: ath9k_htc: Target is unresponsive
> [   42.072759] ath9k_htc: Failed to initialize the device
> [   42.077042] dwc2 3f980000.usb: dwc2_hc_halt() Channel can't be halted
> [   42.078804] usb 1-1.3: ath9k_htc: USB layer deinitialized
> 

**To Reproduce**
1. Just plug in the card and look in dmesg

---

Multiple checked and was not the cable nor the power nor the card itself. Found out its a firmware issue. Waste of my time into thinking it could work for ANY linux out of the box. Got lazy and ordered two Raspi Zero W for who knows I could use it with Nexmon. What could be better is if the Repo was pulled from the main Kali Repo or even better, ParrotOS instead of http://http.re4son-kernel.com/re4son/ repo

Yep, that and this shit right here with txpower causing a wreck with another WN722N v2 card. https://github.com/bettercap/bettercap/issues/614

**Comment by evilsocket** [comment]
"this shit right here" you'll need to have a different attitude and wording if you want help here.
