### ISSUE TITLE
[BUG] Pi4 long init times w/ no screen attached

### ISSUE THREAD

**Issue by l33tLumberjack** [evilsocket/pwnagotchi#570]
**Describe the bug**
When loading pwnagotchi since V1.0.1 on a Pi4 it takes upward of 10+ minutes to initialize the device.

**To Reproduce**
1. Flash any pwnagotchi version later than 1.0.1 on a Pi4 with no display
2. Start pwnagotchi in AUTO mode with the default.yml config
3. tail /var/log/pwnagotchi.log noting times between when the display is initialized and when the webui becomes available

**Expected behavior**
Time to init the display should be less than 30 seconds on a normal boot

**Screenshots**
<img width="731" alt="screenshot" src="https://user-images.githubusercontent.com/9029617/68539014-ed2b8a80-0342-11ea-94d9-2504a3e329c0.png">

**Environment (please complete the following information):**
 - Pwnagotchi version **Tested on 1.2.1 but seen in any version north of but not including 1.0.1**
 - OS version **Pwnagotchi default image**
 - Type of hardware **Pi 4 Model B 4GB**
 - Any additional hardware used **[Geekworm Aluminum Alloy Passive Cooling Case](https://www.amazon.com/dp/B07VD568FB/ref=cm_sw_em_r_mt_dp_U_yY5XDb9DVZAA2) and [SanDisk Ultra PLUS microSDHC UHS-I MicroSD Card (128GB)](https://www.amazon.com/SanDisk-Ultra-microSDHC-Memory-SDSQUSC-128G-ANCMA/dp/B0190M3FFK/ref=sr_1_1?keywords=SanDisk+Ultra+PLUS+microSDHC+UHS-I+Memory+Card+%28SDSQUSC-128G-ANCMA%29+-+128GB)**

**Additional context**
Looks like after the display loads the device works fine. 
Note in this screenshot it took this boot 11 minutes from the time the display was inited to the time it was able to load the webui interface but also note that the bluetooth was able to load independently in the background while this happened. I have also tested this same config with other displays and are seeing the same behavior regardless of screen used.
Ive got a feeling that this may be a bug with how the displays are loaded on this hardware and as such I see 3 possible paths forward.

1. Identify and correct the bug in the way it loads the displays. Improving load times.
2. Break the webui part of the display module into its own code so it can load independently of initializing the displays. Vastly improving load times.
3. Add the option to select NONE as an option for the display which would bypass loading any display code and skip directly to loading the webui if enabled.

**Comment by Arttumiro** [comment]
Commenting here too because this is not an issue, just make ui.display.enabled to false and e inks will be disabled but webui will still work. No need for another useless screen setting for something that can just be disabled, either way atleast for me setting it to ws_2 even when i didnt have a screen caused no issues.
