### ISSUE TITLE
Pwnagotchi login 

### ISSUE THREAD

**Issue by aliforyou** [evilsocket/pwnagotchi#588]
I use raspberry p zero w with my pc screen by hadmi to vaga adapter,  I use the last version of pwnagotchi image and I followed the instructions to buid a  pwnagotchi everything was  fine  but I don't know what is the pwnagotchi login I tried raspberry default user but nothing happen it keep tell me that login is incorrect 
![IMG_20191112_103941](https://user-images.githubusercontent.com/48772865/68661612-84f3c900-053b-11ea-802a-072dc18b256f.jpg)
Sorry for my bad English

**Comment by Arttumiro** [comment]
pi/raspberry
login is pi, password is raspberry
Use passwd after boot to change password to something else

**Comment by spryder89** [comment]
hi 
i have the same issue. 
But the login isnt pi/raspberry on my device, can you help me?
