### ISSUE TITLE
[BUG] webgpsmap plugin does not allow negative lat/lon

### ISSUE THREAD

**Issue by budd3993** [evilsocket/pwnagotchi#611]
**Describe the bug**
webgps map plugin throws errors on negative latitude and longitude values

**To Reproduce**
1. create a ssid.geo.json file with negative longitude or latitude
2. navigate to <pwnagotchi-ip>:8080/plugins/webgpsmap
3. see error in log message that longitude is 0

**Expected behavior**
Render negative lat/lon correctly on map

**Environment (please complete the following information):**
 - Pwnagotchi version 1.2.1 (5f593a4)
 - Type of hardware rpi0w

**Additional context**
The issue occurs in the lines below
https://github.com/evilsocket/pwnagotchi/blob/5f593a4231a231598be70b3d90fcc0f32c1b982a/pwnagotchi/plugins/default/webgpsmap.py#L341-L343

https://github.com/evilsocket/pwnagotchi/blob/5f593a4231a231598be70b3d90fcc0f32c1b982a/pwnagotchi/plugins/default/webgpsmap.py#L354-L356

**Comment by Arttumiro** [comment]
Post it directly into the issues thread for the plugin https://github.com/xenDE/pwnagotchi-plugin-webgpsmap/issues
