### ISSUE TITLE
help me

### ISSUE THREAD

**Issue by 234v244** [evilsocket/pwnagotchi#641]
I use raspberry pi 3 for this project
I can access the web interface of pwnagotchi. But my pwnagotchi doesn't have internet access.

When I do: git clone https://github.com/waveshare/LCD-show.git
It returns: fatal: unable to access 'https://github.com/waveshare/LCD-show.git/': Could not resolve host: github.com
Or when I perform: sudo apt-get update
I get the message: Some index files failed to download. They have been ignored, or old ones used instead.

I don't know what to do so my pwnagotchi can connect to the internet

**Comment by xenDE** [comment]
can u please ask in slack or https://community.pwnagotchi.ai/ ???

thats the wron place here

**Comment by bruvv** [comment]
Same issue here

**Comment by bruvv** [comment]
@234v244 perhaps close this ?
