### ISSUE TITLE
webcfg deleted my config.yml

### ISSUE THREAD

**Issue by miotislucifugis** [evilsocket/pwnagotchi#646]
I had a failed save while using webcfg and it erased all the content of my config.yml.    
Im not sure exactly what happened; whether if it was a pwnagotchi error, or the browser... but after it was auto reset (after clicking save in webcfg)   the pwnagotchi started acting "weird" and i checked the config.yml via nano and it was totally empty.   I actually thought at first that i had mis-typed something and was creating a new file, but no.  Config.yml was just totally empty

 No biggie, as i had a fairly recent backup handy so it was all sorted out easily  but I just thought I should give everyone a heads up that this can happen.

**Comment by dadav** [comment]
Thanks for your report! Will make it more failproof

**Comment by benallard** [comment]
My cfg just disapeared as well. not fun. :(

**Comment by RubenGamerPT** [comment]
mine too...
