### ISSUE TITLE
Pwngrid version in Pwnagotchi 1.3.0

### ISSUE THREAD

**Issue by zeroSocket** [evilsocket/pwnagotchi#647]
I noticed that pwnagotchi 1.3.0 was released with pwngrid 1.10.1 although version 1.10.3 was already available for a few days. Do we need to update the pwngrid to 1.10.3?

**Comment by sayak-brm** [comment]
My pwnagotchi automatically updated pwngrid while running the 1.3.0 image

**Comment by zeroSocket** [comment]
Ok, but updated to 1.10.1 version (in 1.3.0 image) while on github 1.10.3 war already released. That's my point

**Comment by sayak-brm** [comment]
Maybe `pwngrid` v.1.10.3 wasn't ready in time for packaging when building the v1.3.0 image. Either way, the `auto-update` plugin will automatically update your `pwngrid` to the latest version.

![image](https://user-images.githubusercontent.com/5992716/69581824-38a98e00-0ffd-11ea-8c30-64be1ad53f68.png)
