### ISSUE TITLE
Implementation of a Waveshare 1.44 LCD HAT

### ISSUE THREAD

**Issue by Evg33** [evilsocket/pwnagotchi#648]
Can you add support Waveshare 1.44inch LCD HAT ?
https://www.waveshare.com/1.44inch-lcd-hat.htm
https://www.waveshare.com/wiki/1.44inch_LCD_HAT
Driver: ST7735S
Interface: SPI
Display color: RGB, 65K color
Resolution: 128x128
Backlight: LED
Operating voltage: 3.3V

python code examples:  https://www.waveshare.com/w/upload/f/fa/1.44inch-LCD-HAT-Code.7z

**Comment by Evg33** [comment]
![image](https://user-images.githubusercontent.com/7160738/70230728-053bd180-176a-11ea-8c9b-2b47efc56eb5.png)

**Comment by Evg33** [comment]
![image](https://user-images.githubusercontent.com/7160738/70236211-91072b00-1775-11ea-9b07-9803428cbdd2.png)

**Comment by Evg33** [comment]
![image](https://user-images.githubusercontent.com/7160738/70259628-98432e80-179f-11ea-83f6-3c99bdaee725.png)

**Comment by Evg33** [comment]
![image](https://user-images.githubusercontent.com/7160738/70264063-c11bf180-17a8-11ea-95f8-0245785d9a85.png)
black text

**Comment by Evg33** [comment]
Oldscool :) (green terminal)
![image](https://user-images.githubusercontent.com/7160738/70266076-dc88fb80-17ac-11ea-875d-725ecd3070e7.png)

**Comment by Evg33** [comment]
![image](https://user-images.githubusercontent.com/7160738/70286527-93e93680-17dc-11ea-8b7d-d6707d5e0c9d.png)

**Comment by Evg33** [comment]
https://github.com/evilsocket/pwnagotchi/pull/694

**Comment by Evg33** [comment]
![image](https://user-images.githubusercontent.com/7160738/70342304-cd19b900-1865-11ea-82ee-b2029109495c.png)

**Comment by Faludokner** [comment]
Hey, I know thus is years late, but do you mind explaining how do you set a custom background for the pwnagotchi on the hat like that? It's so cool.

**Comment by Evg33** [comment]
> Hey, I know this is years late, but do you mind explaining how do you set a custom background for the pwnagotchi on the hat like that? It's so cool.

It was 2 years ago.
Texts with picture is seen worse.

**Comment by XZCendence** [comment]
> > Hey, I know this is years late, but do you mind explaining how do you set a custom background for the pwnagotchi on the hat like that? It's so cool.
> 
> It was 2 years ago.
> Texts with picture is seen worse.
> 

Can you explain how it was done tho? also how can we change the color of the screen from green to something else

**Comment by V0r-T3x** [comment]
@XZCendence if this can interest you, I just coded a colorized darkmode for the pwnagotchi and a 1.33 waveshare lcd screen ST7789 and I try to make it work on a ST7735S. Now Im actually figuring out how to program a theme manager. 

the link [here](https://github.com/V0r-T3x/pwnagotchi_LCD_colorized_darkmode)

**Comment by XZCendence** [comment]
> @XZCendence if this can interest you, I just coded a colorized darkmode for the pwnagotchi and a 1.33 waveshare lcd screen ST7789 and I try to make it work on a ST7735S. Now Im actually figuring out how to program a theme manager. 
> 
> the link [here](https://github.com/V0r-T3x/pwnagotchi_LCD_colorized_darkmode)

you already told me about this in the discord lol, my username is the same there

**Comment by V0r-T3x** [comment]
haha sorry '^-^ , I just bought a 1.44 hat but it's not working, did you have tried a 1.44 ST7735S with a stuck image of pwnagotchi by curiosity?

**Comment by KalyanSingh05** [comment]
@Evg33 how you did this? Can you please explain the steps!
