### ISSUE TITLE
download and save cracked passwords from wpa-sec on interval

### ISSUE THREAD

**Issue by xenDE** [evilsocket/pwnagotchi#651]
it would be nice if cracked passwords from wpa-secwill be downloaded automaticly and stored in handshakes dir as .pcap.cracked in plaintext - like the quickdic plugin does.

so, extend the wpa-sec plugin with downoad+proccess the cracked pasword list.

steps:

download of the passwordlist:
```
GET https://wpa-sec.stanev.org/?api&dl=1
with Cookie | key=3e47******************6535c
```

process the download:
https://github.com/xenDE/pwnagotchi-tools/blob/master/wpa-sec.founds.insert.py

**Comment by dadav** [comment]
You want to use the file to display it on the map, right?^^

**Comment by xenDE** [comment]
yes.
I already show the passwords in .pcap.cracked created from quickdic plugin.

**Comment by dadav** [comment]
Sounds nice, i will add it^^

**Comment by dadav** [comment]
Added this: https://github.com/dadav/pwnagotchi/tree/feature/wpa-sec-download

but need to test ^^

**Comment by dadav** [comment]
I'd like to keep it raw and let other plugins parse it for themself

**Comment by xenDE** [comment]
looks good, but it downloads only if it has a new handshake for upload.

I need to think about "other plugins parse it for themself" - not sure what's the best way.

the potfile is only usable for extract password - implement the parser at every plugin that wants to have the password is not a good way IMHO.

**Comment by xenDE** [comment]
is working.
only a log message i miss

**Comment by dadav** [comment]
> 
> 
> looks good, but it downloads only if it has a new handshake for upload.
> 
> I need to think about "other plugins parse it for themself" - not sure what's the best way.
> 
> the potfile is only usable for extract password - implement the parser at every plugin that wants to have the password is not a good way IMHO.

well, its one for-loop and not really "parsing" because the data is seperated by ":"^^

```
for line in file:
  bssid,stamac,ssid,pw = line.split(":")
```

Yes, it only downloads if a new handshake is found...I don't want to implement another "tracking" file to track the last check.

**Comment by dadav** [comment]
Derek close

**Comment by agent932** [comment]
Would there be a way to add the cracked networks to the ignore list so the pwnagotchi stops trying to get new handshakes?

**Comment by itsdarklikehell** [comment]
> Would there be a way to add the cracked networks to the ignore list so the pwnagotchi stops trying to get new handshakes?

I second this!☝️

**Comment by agent932** [comment]
👍

**Comment by jacopotediosi** [comment]
Onlinehashcrack (starting from PR #821) saves cracked passwords into .pcap.cracked files (one for each password), allowing them to be usable with the webgpsmap plugin.
It would be nice if wpa-sec did the same (?)

**Comment by jacopotediosi** [comment]
Just made the PR #1248 to save wpasec cracked password into individual .pcap.cracked password as discussed above
