### ISSUE TITLE
Being able to disable deauth while running

### ISSUE THREAD

**Issue by maxxer** [evilsocket/pwnagotchi#661]
**Is your feature request related to a problem? Please describe.**

I'd like to be able to disable and enable `deauth` on runtime.

**Describe the solution you'd like**

It would be great to have an additional button on the webui to enable/disable the feature. It's useful for example if you're entering a meeting and don't want do *disturb*.

Maybe related to #206.

**Describe alternatives you've considered**

Right now the only option coming to my mind is to ssh to the device, change the setting and restart.

**Comment by dadav** [comment]
Isn't this solved by `webcfg` plugin? You can change the setting there..

**Comment by maxxer** [comment]
Likely, I didn't check for recent plugins before posting 🤦‍♂ 

I'm closing,  will reopen eventually. Thanks!

**Comment by dadav** [comment]
Derek close
