### ISSUE TITLE
Bigger fonts

### ISSUE THREAD

**Issue by RChadwick7** [evilsocket/pwnagotchi#676]
Self explanatory, especially for those of us without perfect vision :)

**Comment by NarenHT** [comment]
Not from the pwnagotchi team but font size can be edited. 
/usr/local/lib/python3.7/dist-packages/pwnagotchi/ui/fonts.py

**Comment by dadav** [comment]
Problem is: The bigger font will overlaps with the elements. Please open a thread in community.pwnagotchi.ai if you have an idea how to fix that.

**Comment by dadav** [comment]
You can change the font now^^ I'll close this

**Comment by dadav** [comment]
Derek close
