### ISSUE TITLE
Negative Uptime with RTC

### ISSUE THREAD

**Issue by RChadwick7** [evilsocket/pwnagotchi#688]
I installed a RTC, set the time correctly earlier, and added this line to /boot/config.txt:
dtoverlay=i2c-rtc,ds3231
Now when I start up Pwnagotchi, I get UP time as -5:27:39, and it just sits there. Rebooting shows the same thing (The screen refreshes during reboot)

**Comment by RChadwick7** [comment]
Nevermind. Disabling the fake hwclock fixed it.

**Comment by cubeDHS2017** [comment]
> Nevermind. Disabling the fake hwclock fixed it.

How would I be able to do that to fix the problem?
