### ISSUE TITLE
error while loading Wpa-sec.py[BUG]

### ISSUE THREAD

**Issue by miotislucifugis** [evilsocket/pwnagotchi#692]
**Describe the bug**
Ive realized that my  pwnagitchi has not been uploading any new handshakes to wpa-sec.stanev.org for about a week or so.  I just noticed this in the log on start up:
`pwnagotchi-launcher[3548]: [2019-12-05 05:03:07,860] [WARNING] error while loading /usr/local/lib/python3.7/dist-packages/pwnagotchi/plugins/default/wpa-sec.py: Expecting ',' delimiter: line 1 column 16434 (char 16433)`
Any ideas what is going on here?   It worked before, after going to 1.3.0.    As far as I know I made no changes to any to the wpa-sec.py files.   My config did get wiped in a webcfg error, but I restored it 

**To Reproduce**
1. restart pwnagotchi
2. observe logs

**Environment (please complete the following information):**
 - Pwnagotchi version 1.3.0
 waveshare v2, upslite, 
bluetooth gps connected on dev/rfcomm1

**Comment by miotislucifugis** [comment]
update: i removed the file and made a new one and now it works. (shrug)  
curious tho as to what went wrong...

**Comment by dadav** [comment]
This happens when the tracking file is corrupted. This should be fixed in #664

**Comment by dadav** [comment]
Derek close
