### ISSUE TITLE
Replace string formatting with logging library laziness

### ISSUE THREAD

**Issue by alanyee** [evilsocket/pwnagotchi#697]
https://docs.python.org/3/howto/logging.html#optimization describes the laziness of logging. Essentially, replace something like
```
logging.info("it looks like %s is not in range anymore :/" % who)
```
with

```
logging.info("it looks like %s is not in range anymore :/", who)
```

I will be doing these changes in small increments to prevent having a single big PR requiring a long code review.

**Comment by dadav** [comment]
Like #690 ?

**Comment by alanyee** [comment]
There are more files that lack the optimization.

**Comment by evilsocket** [comment]
for the record https://github.com/evilsocket/pwnagotchi/commit/a0a790635a4662a0d6b6d785ace70fe3f0af7f89
