### ISSUE TITLE
ssh in to the pi.

### ISSUE THREAD

**Issue by Leon-NL** [evilsocket/pwnagotchi#703]
My computer doesn't see the pi as a ethernet adapter but as a com port. I have tried multiple computers and cables. I am running windows 10. If some knows a solution or has experiend this problem before i would really like to know how to fix this.

Thanks a lot.

**Comment by Arttumiro** [comment]
https://community.pwnagotchi.ai/t/windows-10-connection-sharing-guide-thing-for-rpi0w-pwnagotchi-v-1-4-0-and-earlier/273/2
