### ISSUE TITLE
Auto Update fails 1.3.0 ->1.4.1

### ISSUE THREAD

**Issue by miotislucifugis** [evilsocket/pwnagotchi#704]
Auto update keeps failing on both of my pwnagotchis

It starts off good.  It downloads the package.   it does a lot of this stuff:
`Dec 08 00:36:10 chacha pwnagotchi-launcher[682]:   inflating: /tmp/updates/pwnagotchi/pwnagotchi-1.4.1/scripts/backup.sh
Dec 08 00:36:10 chacha pwnagotchi-launcher[682]:   inflating: /tmp/updates/pwnagotchi/pwnagotchi-1.4.1/scripts/changelog.sh`
then a lot of this:
`Dec 08 00:36:10 chacha pwnagotchi-launcher[682]: warning:  cannot set modif./access times for /tmp/updates/pwnagotchi/pwnagotchi-1.4.1/pwnagotchi/locale/ro/LC_MESSAGES/
Dec 08 00:36:10 chacha pwnagotchi-launcher[682]:           No such file or directory
Dec 08 00:36:10 chacha pwnagotchi-launcher[682]: warning:  cannot set permissions for /tmp/updates/pwnagotchi/pwnagotchi-1.4.1/pwnagotchi/locale/ro/LC_MESSAGES/
Dec 08 00:36:10 chacha pwnagotchi-launcher[682]:           No such file or directory
Dec 08 00:36:10 chacha pwnagotchi-launcher[682]: warning:  set times/attribs failed for /tmp/updates/pwnagotchi/pwnagotchi-1.4.1/pwnagotchi/locale/ro/LC_MESSAGES/`
followed by this:
`Dec 08 00:36:11 chacha pwnagotchi-launcher[682]:      failed setting times/attribs for 45 dir entries[2019-12-08 00:36:11,541] [INFO] [update] installing pwnagotchi ...
Dec 08 00:36:11 chacha pwnagotchi-launcher[682]: [2019-12-08 00:36:11,681] [WARNING] update for evilsocket/pwnagotchi available (local version is '1.3.0'): https://github.com/evilsocket/pwnagotchi/archive/v1.4.1.zip
`
the unit then reboots, but is still in 1.3.0.

Any ideas what is going on here and/or how i can fix it? 
thanks

**Comment by Arttumiro** [comment]
https://twitter.com/pwnagotchi/status/1203321283305443329
