### ISSUE TITLE
[BUG] Unable to connect via Bluetooth

### ISSUE THREAD

**Issue by RChadwick7** [evilsocket/pwnagotchi#730]
I have tried multiple Raspberry Pi Zero W's, connecting to either a phone or a laptop. From the Pi, I find the MAC of the remote device, successfully pair it, trust it, but I can never get it to actually connect.

**Comment by H4ck3r404** [comment]
It could be because of missing bt-nap. See #377 for more info.

**Comment by dadav** [comment]
If you tried multiple raspis and it didnt work, there are 2 possibilities:
1. Your config is wrong
2. Your phone isn't in tether mode

**Comment by RChadwick7** [comment]
I wasn't aware that not having Bluetooth tethering would prevent it from connecting. It could be my phone, which doesn't have a Bluetooth Tether mode.

**Comment by dadav** [comment]
So, no bug :)

**Comment by dadav** [comment]
Derek close
