### ISSUE TITLE
Implement an AP whitelist system in wpa-sec plugin, similar to onlinehashcrack

### ISSUE THREAD

**Issue by ArnCo** [evilsocket/pwnagotchi#733]
**Is your feature request related to a problem? Please describe.**
Do not submit hanshakes to wpa-sec for a given list of access points.

**Describe the solution you'd like**
Define a whitelist of access points in config.yml to be ignored by wpa-sec plugin.

**Describe alternatives you've considered**
None

**Additional context**
I'll submit a pull request shortly.

**Comment by Evg33** [comment]
Need "\_" in SSID's.

**Comment by dadav** [comment]
Derek close
