### ISSUE TITLE
[BUG]Auto-Update plugin not updating pwnagotchi

### ISSUE THREAD

**Issue by benallard** [evilsocket/pwnagotchi#743]
**Describe the bug**
The auto-update plugins keeps rebooting my gotchi (once an hour), but doesn't update it.

**To Reproduce**
1. Install older image
2. give internet to your gotchi
3. see it reboot
4. again and again ...
5. again and again ...

**Expected behavior**
Reboot once, enjoy the new stuff.

**Comment by LoganMD** [comment]
Pretty sure everyone is having this issue, me included

**Comment by dadav** [comment]
Which older image?

**Comment by benallard** [comment]
1.3.0 and 1.4.1 had the issue.

**Comment by th0rtz** [comment]
Same problem in 1.3.0

Error log on update : 
>[2019-12-21 13:37:09,525] [WARNING] update for evilsocket/pwnagotchi available (local version is '1.3.0'): https://github.com/evilsocket/pwnagotchi/archive/v1.4.2.zip
>[2019-12-21 13:37:11,251] [INFO] [update] downloading https://github.com/evilsocket/pwnagotchi/archive/v1.4.2.zip to /tmp/updates/pwnagotchi/pwnagotchi_1.4.2.zip ...
sh: 0: getcwd() failed: No such file or directory
> Could not install packages due to an EnvironmentError: [Errno 2] No such file or directory

> [2019-12-21 13:37:32,028] [INFO] [update] extracting /tmp/updates/pwnagotchi/pwnagotchi_1.4.2.zip to /tmp/updates/pwnagotchi ...

**Comment by dadav** [comment]
1.3.0 is known to have an update-bug. But I thought 1.4.1 is fine :/

**Comment by xBelladonna** [comment]
Hmm, funny you should mention that, I have experienced update problems on 1.4.1 too, mentioned in my comment on #731, but I'm not sure if it's the same issue as described here. Anyway, I stopped services by systemd and updated all components manually as a workaround.

**Comment by LoganMD** [comment]
Having update problems too, just won't update from 1.4.1 to 1.4.2. Had the same problem with 1.3.0.

**Comment by th0rtz** [comment]
Manual update work fine from 1.3.0 to 1.4.2

**Comment by a60wattfish** [comment]
The downloader for the update isn't following the redirect to the download file, so just saves the HTML header instead of the zip.

**Comment by phr34k0** [comment]
Looks like it needs to do some version checking on that line 214 instead of just

> if num_installed > 0:

```
def on_internet_available(self, agent):
.
.
                if num_installed > 0:
                    display.update(force=True, new_data={'status': 'Rebooting ...'})
                    pwnagotchi.reboot()

            except Exception as e:
                logging.error("[update] %s" % e)
```

**Comment by dadav** [comment]
So, I think it's fixed, if not we will reopen.

**Comment by dadav** [comment]
Derek close

**Comment by alessaba** [comment]
> #731

Can you pleas explain what you mean by "updating all the components manually"?
do you clone the project to the pi and then overwrite the Pwnagotchi folders?
thanks in advance

**Comment by phr34k0** [comment]
> > #731
> 
> Can you pleas explain what you mean by "updating all the components manually"?
> do you clone the project to the pi and then overwrite the Pwnagotchi folders?
> thanks in advance

Nope. Delete everything and throw your pi out the window

**Comment by alessaba** [comment]
> > > #731
> > 
> > 
> > Can you pleas explain what you mean by "updating all the components manually"?
> > do you clone the project to the pi and then overwrite the Pwnagotchi folders?
> > thanks in advance
> 
> Nope. Delete everything and throw your pi out the window

I just wanted to know what folders i need to overwrite. Thanks anyway for the professional behavior 👍

**Comment by phr34k0** [comment]
> > > > #731
> > > 
> > > 
> > > Can you pleas explain what you mean by "updating all the components manually"?
> > > do you clone the project to the pi and then overwrite the Pwnagotchi folders?
> > > thanks in advance
> > 
> > 
> > Nope. Delete everything and throw your pi out the window
> 
> I just wanted to know what folders i need to overwrite. Thanks anyway for the professional behavior

LOL. The answer is written all over above. Yes. Manual is delete everything and git clone.
