### ISSUE TITLE
Integrate dnsmasq to give DHCP lease on usb0

### ISSUE THREAD

**Issue by xBelladonna** [evilsocket/pwnagotchi#748]
Issue #481 was raised to use a DHCP server to configure network for usb0 when in manual mode instead of having to manually configure the adapter.

~~I would like to submit a pull request to address this issue, but before I open it, I must discuss some points.~~
All issues with timeouts/lease MAC mismatch etc have been solved.
Pull request #777 contains an implementation of dnsmasq with the local DNS disabled and only DHCP serving.

Now, this requires a change to the documentation due to the change in the way the network over USB is configured It is not a breaking change since the static configuration still works without any trouble, DHCP is a separate apparatus. However, the [entire section about manual network configuration](https://pwnagotchi.ai/configuration/#connect-to-your-pwnagotchi) can be made optional, or turned into a protip if users experience issues with DHCP. 
There is also the [static RNDIS gadget community hack](https://pwnagotchi.ai/community/#static-rdnis-gadget-to-avoid-reconfiguration-everytime-you-plug-it-to-the-computer) that is automatically applied at boot by the above PR, which must be considered also.
I'm a little unsure how to go about this, and would appreciate any help from those more experienced than me. Which option do you think is better?

**Comment by xBelladonna** [comment]
First mistake, MUST configure DHCP lease time of 2 minutes otherwise lease time defaults to infinity!
Second, it seems all this problem about lease times/symlinking leases file to oblivion can be solved by [this community hack in the documentation](https://pwnagotchi.ai/community/#static-rdnis-gadget-to-avoid-reconfiguration-everytime-you-plug-it-to-the-computer)

**Comment by dadav** [comment]
Derek close
