### ISSUE TITLE
Bluetooth connection without requiring tether

### ISSUE THREAD

**Issue by RChadwick7** [evilsocket/pwnagotchi#756]
While there appear to be many phones that do not allow Bluetooth Tethering (None of my devices do), and Pwnagotchi doesn't need Internet for someone to log into the interface or terminal, it would be great if Bluetooth could be made to work without tethering.

**Comment by gtsatsis** [comment]
@RChadwick7, As far as I'm aware, Bluetooth Tethering is the only way to enable IP communication through Bluetooth.

Sure, internet access isn't required but the internet protocol is.

**Comment by RChadwick7** [comment]
What about a Bluetooth PAN?

**Comment by gtsatsis** [comment]
@RChadwick7, Yeah, but that's what is carrier-locked on many phones because Plans are usually able to share the host connection.

Afaik, it's just what Bluetooth Tethering does, makes a PAN & Shares host.

**Comment by foreign-sub** [comment]
Hi @RChadwick7 ,
As @gtsatsis said, the issue here is that without bluetooth tethering your phone does not add the PAN to the bluetooth profile sent to your pwnagotchi, i don't know of any workaround, sorry.

PS: Always enable bluetooth tethering before pairing otherwise the bluetooth profile will miss the PAN  even if you enable it after.

**Comment by RChadwick7** [comment]
I wish I could enable Bluetooth tethering, but my phone doesn't have that option. Apparently T-Mobile in the US likes to disable it. My Galaxy S7, Galaxy S10, and an LG Tablet all are missing the Bluetooth Tethering option.
Do you know if Pwnagotchi would work with Pdanet?

**Comment by dadav** [comment]
If you can't tether, you won't be able to create a connection :(

**Comment by dadav** [comment]
Derek close
