### ISSUE TITLE
 [BUG] Automata.py exception error. NameError: name (error) is not defined

### ISSUE THREAD

**Issue by phr34k0** [evilsocket/pwnagotchi#765]
In Automata.py change line to pass to avoid exception error in /var/log/pwnagotchi.log and /var/log/syslog

`    def _on_error(self, who, e):
                                          pass
`

**Comment by dadav** [comment]
What name error?

**Comment by phr34k0** [comment]
Something with "NameError: name 'error' is not defined" in in str(e): 

It gets pretty annoying looking at the logs

**Comment by dadav** [comment]
Should be fixed by this:
https://github.com/evilsocket/pwnagotchi/commit/9d56c97aa51b3a031623a184e659787fa7db5144

**Comment by dadav** [comment]
Derek close
