### ISSUE TITLE
[BUG] typo in service to be disabled in Ansible YAML

### ISSUE THREAD

**Issue by espinielli** [evilsocket/pwnagotchi#772]
**Describe the bug**
The name of a service to be disabled has a typo, `rasberrypi-net-mods` should be `raspberrypi-net-mods` (missing **p**)

**Expected behavior**
Disable the relevant service in the image being built.

**Comment by dadav** [comment]
Good catch!

**Comment by dadav** [comment]
Derek assign dadav

**Comment by dadav** [comment]
Derek close
