### ISSUE TITLE
Question about Personality and AI

### ISSUE THREAD

**Issue by CyrisXD** [evilsocket/pwnagotchi#775]
I understand that the AI mode will learn the best way to attack networks around you, but if you set deauth to false in a personality. When AI kicks in will it re-enable the deauth? 

Most times I won't want to deauth. If AI does indeed re-enable deauth is it possible to set multiple personalities/profiles  (AI disabled) to quickly change between when I do want to deauth to when I want to stay silent? 

But then of course I'd lose out on the knowledge the AI has gained and rely on basic channel scanning. 

Cheers

**Comment by dadav** [comment]
It won't enable deauth automatically :)

**Comment by CyrisXD** [comment]
@dadav Thanks, that's good to hear :)
