### ISSUE TITLE
[BUG] Error while starting AI since the switch to TOML

### ISSUE THREAD

**Issue by hectorm** [evilsocket/pwnagotchi#791]
**Describe the bug**
Since the switch to TOML the AI produces an exception during the load.

**To Reproduce**
Run `pwnagotchi` without any modification.

**Expected behavior**
Do not produce any exception.

**Environment (please complete the following information):**
 - Pwnagotchi version: 52015014b41264db7cfd97719de14e612b93274c.
 - OS version: Raspbian.
 - Type of hardware: Raspberry Pi Zero W.

**Additional context**
Stack trace:
```
[2020-01-14 22:17:22,560] [ERROR] error while starting AI
Traceback (most recent call last):
  File "/usr/lib/pwnagotchi/lib/python3.7/site-packages/pwnagotchi/ai/__init__.py", line 45, in load
    a2c = A2C(MlpLstmPolicy, env, **config['params'])
  File "/usr/lib/pwnagotchi/lib/python3.7/site-packages/stable_baselines/a2c/a2c.py", line 86, in __init__
    self.setup_model()
  File "/usr/lib/pwnagotchi/lib/python3.7/site-packages/stable_baselines/a2c/a2c.py", line 118, in setup_model
    self.n_steps, n_batch_train, reuse=True, **self.policy_kwargs)
  File "/usr/lib/pwnagotchi/lib/python3.7/site-packages/stable_baselines/common/policies.py", line 682, in __init__
    layer_norm=False, feature_extraction="mlp", **_kwargs)
  File "/usr/lib/pwnagotchi/lib/python3.7/site-packages/stable_baselines/common/policies.py", line 425, in __init__
    input_sequence = batch_to_seq(extracted_features, self.n_env, n_steps)
  File "/usr/lib/pwnagotchi/lib/python3.7/site-packages/stable_baselines/a2c/utils.py", line 174, in batch_to_seq
    tensor_batch = tf.reshape(tensor_batch, [n_batch, n_steps, -1])
  File "/usr/lib/pwnagotchi/lib/python3.7/site-packages/tensorflow/python/ops/gen_array_ops.py", line 7179, in reshape
    "Reshape", tensor=tensor, shape=shape, name=name)
  File "/usr/lib/pwnagotchi/lib/python3.7/site-packages/tensorflow/python/framework/op_def_library.py", line 610, in _apply_op_helper
    param_name=input_name)
  File "/usr/lib/pwnagotchi/lib/python3.7/site-packages/tensorflow/python/framework/op_def_library.py", line 60, in _SatisfiesTypeConstraint
    ", ".join(dtypes.as_dtype(x).name for x in allowed_list)))
TypeError: Value passed to parameter 'shape' has DataType float32 not in list of allowed values: int32, int64
[2020-01-14 22:17:22,563] [WARNING] [ai] AI not loaded!
```

**Comment by natur3kid** [comment]
Hi, same problem Here, when updating the 1.4.3 to the toml switch.

Jan 15 10:13:15 pwnagotchi pwnagotchi-launcher[1389]: [2020-01-15 10:13:15,817] [ERROR] error while starting AI
Jan 15 10:13:15 pwnagotchi pwnagotchi-launcher[1389]: Traceback (most recent call last):
Jan 15 10:13:15 pwnagotchi pwnagotchi-launcher[1389]:   File "/usr/local/lib/python3.7/dist-packages/pwnagotchi/ai/__init__.py", line 45, in load
Jan 15 10:13:15 pwnagotchi pwnagotchi-launcher[1389]:     a2c = A2C(MlpLstmPolicy, env, **config['params'])
Jan 15 10:13:15 pwnagotchi pwnagotchi-launcher[1389]:   File "/usr/local/lib/python3.7/dist-packages/stable_baselines/a2c/a2c.py", line 86, in __init__
Jan 15 10:13:15 pwnagotchi pwnagotchi-launcher[1389]:     self.setup_model()
Jan 15 10:13:15 pwnagotchi pwnagotchi-launcher[1389]:   File "/usr/local/lib/python3.7/dist-packages/stable_baselines/a2c/a2c.py", line 118, in setup_model
Jan 15 10:13:15 pwnagotchi pwnagotchi-launcher[1389]:     self.n_steps, n_batch_train, reuse=True, **self.policy_kwargs)
Jan 15 10:13:15 pwnagotchi pwnagotchi-launcher[1389]:   File "/usr/local/lib/python3.7/dist-packages/stable_baselines/common/policies.py", line 682, in __init__
Jan 15 10:13:15 pwnagotchi pwnagotchi-launcher[1389]:     layer_norm=False, feature_extraction="mlp", **_kwargs)
Jan 15 10:13:15 pwnagotchi pwnagotchi-launcher[1389]:   File "/usr/local/lib/python3.7/dist-packages/stable_baselines/common/policies.py", line 425, in __init__
Jan 15 10:13:15 pwnagotchi pwnagotchi-launcher[1389]:     input_sequence = batch_to_seq(extracted_features, self.n_env, n_steps)
Jan 15 10:13:15 pwnagotchi pwnagotchi-launcher[1389]:   File "/usr/local/lib/python3.7/dist-packages/stable_baselines/a2c/utils.py", line 174, in batch_to_seq
Jan 15 10:13:15 pwnagotchi pwnagotchi-launcher[1389]:     tensor_batch = tf.reshape(tensor_batch, [n_batch, n_steps, -1])
Jan 15 10:13:15 pwnagotchi pwnagotchi-launcher[1389]:   File "/usr/lib/python3/dist-packages/tensorflow_core/python/ops/gen_array_ops.py", line 7714, in reshape
Jan 15 10:13:15 pwnagotchi pwnagotchi-launcher[1389]:     "Reshape", tensor=tensor, shape=shape, name=name)
Jan 15 10:13:15 pwnagotchi pwnagotchi-launcher[1389]:   File "/usr/lib/python3/dist-packages/tensorflow_core/python/framework/op_def_library.py", line 631, in _apply_op_helper
Jan 15 10:13:15 pwnagotchi pwnagotchi-launcher[1389]:     param_name=input_name)
Jan 15 10:13:15 pwnagotchi pwnagotchi-launcher[1389]:   File "/usr/lib/python3/dist-packages/tensorflow_core/python/framework/op_def_library.py", line 60, in _SatisfiesTypeConstraint
Jan 15 10:13:15 pwnagotchi pwnagotchi-launcher[1389]:     ", ".join(dtypes.as_dtype(x).name for x in allowed_list)))
Jan 15 10:13:15 pwnagotchi pwnagotchi-launcher[1389]: TypeError: Value passed to parameter 'shape' has DataType float32 not in list of allowed values: int32, int64
Jan 15 10:13:15 pwnagotchi pwnagotchi-launcher[1389]: [2020-01-15 10:13:15,909] [WARNING] [ai] AI not loaded!

I was on Version 1.4.3 (where the AI loaded) then did a git pull and pip3 install .
