### ISSUE TITLE
Question: pcap file overwrittens or supplemented with new handshakes and pmkid?

### ISSUE THREAD

**Issue by LowSkillDeveloper** [evilsocket/pwnagotchi#812]
Yesterday I grabbed a handshake from the "dlink" point, today again I grabbed a couple of new handshakes from this point.
I have a question.
**The pcap file in which the handshake is stored is it overwritten or supplemented with new handshakes and pmkid?**
After all, having a working handshake, it can be overwritten not valid. And that is bad.

**Comment by zeroSocket** [comment]
The handshakes are append to file, not overwritten... if you see your near-home's pcap file is easily greater than others pcap file
