### ISSUE TITLE
Missing firmware-ralink

### ISSUE THREAD

**Issue by LowSkillDeveloper** [evilsocket/pwnagotchi#818]
Need to add "firmware-ralink" package, to be able to work with all ralink adapters.

**Comment by LowSkillDeveloper** [comment]
Also, as I understand it. You have banned updating firmware for firmware-atheros firmware-brcm8021 firmware-misc-nonfree firmware-realtek.
I think for this package will also need to be do this.

**Comment by dadav** [comment]
Which version of the package works for you?

**Comment by dadav** [comment]
`firmware-ralink` is a dummy package and contains just changelog files^^

**Comment by dadav** [comment]
Derek close
