### ISSUE TITLE
[BUG] when starting webui through chromeium command line, stuck on loading.

### ISSUE THREAD

**Issue by xal3xhx** [evilsocket/pwnagotchi#819]
current hardware is, raspberry pi 4 with 5in touch display connected using adafruit dpi hat.
i have the pi boot into desktop mode and open chromium using this command.

chromium-browser --disable-infobars --kiosk "http://username:password@localhost:8080"

chromium will launch just fine and go to the url, but it gets stuck on a loading circle in the middle of the screen, https://i.imgur.com/zrc7KZ8.png

**Comment by xal3xhx** [comment]
found a sorta ok workaround, if i save the creds in chrome and remove the username and password from the command, it will start and you just have to hit ok to login

**Comment by dadav** [comment]
Derek assign dadav
