### ISSUE TITLE
[BUG] Web UI changes not saved - Rp 3B+

### ISSUE THREAD

**Issue by mgagnequebec** [evilsocket/pwnagotchi#829]
**Describe the bug**
On the rasperry pi 3b+, after a fresh install + update, the web ui won't save changes I make. 

( my fresh install booted without lan cable pluged in the first time, not sure if it matters)
**To Reproduce**

I tried the following in MANU mode and AUTO mode, just to see if that changes anything (same result though) :

1. I accessed the web ui through 192.168.0.102:8080 
2. Went to plugin tab. 
3. Enabled the webcfg (couldnt click it until I switched to another tab and came back) 
4. Made changes (added bt mac and set option for this to true) 
5. Saved my changes
6. Putty ssh -> 192.168.0.102:22
7. login
8. sudo su
9. nano /etc/pwnagotchi/config.yml
10. The file is the same as it was at first boot (i used the default; as shown in "Usage" section) 

**Expected behavior**
Changes saved to config.yml

**Environment (please complete the following information):**
 - Pwnagotchi version (pwnver is broken so not sure, but I just did a git pull + pip3 install) 
 - Raspberry pi 3b +

**Comment by xBelladonna** [comment]
If you pulled latest source from the repo you will be using toml config not yaml. Edit `/etc/pwnagotchi/config.toml` instead.

**Comment by mgagnequebec** [comment]
Ah gotcha, I see the thread about it now. Thanks for the info, I'll see if I can get bt-tether enabled in the toml then

**Comment by LowSkillDeveloper** [comment]
This means that the webcfg plugin is not rewritten for the new format, i think.
Switching to toml will create many problems and misunderstandings at the beginning. Need to change not only the instructions for users, but also rewrite the plugins...

**Comment by mgagnequebec** [comment]
It's actually much easier with toml, even without the web ui working. So I'd say this change is a plus.

This project is so amazing, I wish I could contribute more but I am still very new to the project. I will test as much as I can though.

**Comment by dadav** [comment]
Derek close
