### ISSUE TITLE
ImportError: cannot import name 'url_encode' from 'werkzeug'

### ISSUE THREAD

**Issue by tutasla** [evilsocket/pwnagotchi#831]
Currently when running commands like `pwnagotchi -h` it fails with
`ImportError: cannot import name 'url_encode' from 'werkzeug'` error.

Seems like Werkzeug deprecated this function in 1.0.0 (released Feb 7, 2020) which is what currently gets installed in requirements.txt with flask-wtf==0.14.2 (Werkzeug>=0.14)

To fix it, upgrade to `flask-wtf==0.14.3`

See
lepture/flask-wtf@8b02899

**Steps to reproduce:**
- wget "https://github.com/evilsocket/pwnagotchi/archive/v1.4.3.zip"
- unzip v1.4.3.zip
- cd pwnagotchi-1.4.3
- sudo pip3 install -r requirements.txt
- sudo pip3 install .
- pwnagotchi -h

**Tested environment:**
- pwnagotchi 1.4.3
- Raspbian GNU/Linux 10 (buster)
- Raspberry Pi 3 Model B Plus Rev 1.3

**Comment by dadav** [comment]
Derek close
