### ISSUE TITLE
[BUG] Plugins tab not working in web UI

### ISSUE THREAD

**Issue by simonasGit** [evilsocket/pwnagotchi#839]
**Describe the bug**
When in web UI, the plugins tab isn't working: cannot click on plugins settings (the titles) except "session-stats" (underlined and clickable), although the settings won't show up either.
Also, if I enable any of these plugins, nothing changes in config.yml file in 
/etc/pwnagotchi/config.yml
**To Reproduce**
**1.** Plugged my Pwnagotchi into the data port on RPi0W and booted into manu mode,
**2.** Logged into web UI at 10.0.0.2:8080,
**3.** Clicked on plugins tab.

**When enabling plugins:**
**1.** Click on "Enable" in plugins tab,
**2.** ssh pi@10.0.0.2
**3.** cd /etc/pwnagotchi/
**4.** nano config.yml 
**5.** nothing has changed to config file.

**Expected behavior**
Expected to be able to click on plugins settings and enabling plugins in web UI to make changes to config.yml file.

**Environment:**
 - **Pwnagotchi version:** 1.4.3 [latest release]
 - **OS version:** Raspbian GNU/Linux 10 (buster)
 - **Type of hardware:** Raspberry Pi 0 W
 - **Any additional hardware used:** I2C Real Time Clock
**Screenshot:**
![Screenshot from 2020-03-18 15-44-56](https://user-images.githubusercontent.com/52699584/76967109-db747800-691e-11ea-98af-80e92a72691c.png)

**Comment by dadav** [comment]
Derek close
