### ISSUE TITLE
DFRobot V2 support

### ISSUE THREAD

**Issue by misterf13** [evilsocket/pwnagotchi#856]
**Is your feature request related to a problem? Please describe.**
It seems that only dfrobot e-ink v1 is supported. The v2 screens use a new library it seems. https://github.com/DFRobot/DFRobot_RPi_Display_V2 instead of https://github.com/DFRobot/DFRobot_RPi_Display

**Describe the solution you'd like**
Maybe have dfrobot support like the waveshares. dfrobot_1 and dfrobot_2

**Describe alternatives you've considered**

**Additional context**
I got it to work, but not sure how clean this is, etc.
https://github.com/misterf13/pwnagotchi/commit/faddca544057fd6b1448b32fe489d8e8a1f2cbf9

**Comment by dadav** [comment]
looks good to me, cherry-picked it

**Comment by nimbo78** [comment]
@dadav 
config.toml:
```
ui.display.enabled = true
ui.display.type = "dfrobot"
ui.display.color = "black"
```

```
root@pwnagotchi:/home/pi# pwnagotchi
unsupported display type dfrobot
```
am i doing something wrong?

**Comment by misterf13** [comment]
> @dadav
> config.toml:
> 
> ```
> ui.display.enabled = true
> ui.display.type = "dfrobot"
> ui.display.color = "black"
> ```
> 
> ```
> root@pwnagotchi:/home/pi# pwnagotchi
> unsupported display type dfrobot
> ```
> 
> am i doing something wrong?

Try "dfrobot_1" or "dfrobot_2" depending on what version you have.

**Comment by nimbo78** [comment]
> 
> 
> > @dadav
> > config.toml:
> > ```
> > ui.display.enabled = true
> > ui.display.type = "dfrobot"
> > ui.display.color = "black"
> > ```
> > 
> > 
> > ```
> > root@pwnagotchi:/home/pi# pwnagotchi
> > unsupported display type dfrobot
> > ```
> > 
> > 
> > am i doing something wrong?
> 
> Try "dfrobot_1" or "dfrobot_2" depending on what version you have.

yeap, now it works :) thnx a lot
may be someone could edit this instructions - https://pwnagotchi.ai/configuration/#initial-configuration ?

**Comment by nimbo78** [comment]
> 
> 
> > @dadav
> > config.toml:
> > ```
> > ui.display.enabled = true
> > ui.display.type = "dfrobot"
> > ui.display.color = "black"
> > ```
> > 
> > 
> > ```
> > root@pwnagotchi:/home/pi# pwnagotchi
> > unsupported display type dfrobot
> > ```
> > 
> > 
> > am i doing something wrong?
> 
> Try "dfrobot_1" or "dfrobot_2" depending on what version you have.

also, is there any chance to use 2 buttons? with gpio_buttons plugin or something alse could help me?

**Comment by misterf13** [comment]
In your main config you probably need the following.

```
gpio_buttons:
    enabled: true
      gpios:
        21: 'some command'
        22: 'some other command'
```

Check out the code here for more info. :)

https://github.com/evilsocket/pwnagotchi/blob/7de512103345454ff6ff168cf04a7b476b4bb090/pwnagotchi/plugins/default/gpio_buttons.py#L29
