### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by ReconPirate** [evilsocket/pwnagotchi#863]
**Describe the bug**
The bug in question is my pwnagotchi skipped from 1.5.1 to 1.5.3 via auto update, and now seems to pwn no networks, it still deauths and caused handshakes to pass in it's range by force via WiFi pineapple and still nothing. 
**To Reproduce**
1 be on 1.5.1 and auto update 
**Expected behavior**
Still associates still deauths, shows so in dmesg, but nothing.  Any clues before I do a clean wipe?

**Comment by colossus700** [comment]
I had the same issue and doing a full reinstall and reloading the handshakes/brain from the backup fixed it.

**Comment by miotislucifugis** [comment]
Im in the same boat... was hoping to avoid a full reinstall. :(

**Comment by dadav** [comment]
Please try: `bettercap -eval "caplets.update;q"` and reboot

**Comment by miotislucifugis** [comment]
That seems to have worked for me.  Phew!
Thanks!

**Comment by ReconPirate** [comment]
Seems to have fixed my issues as well.  Thanks for the help :3
