### ISSUE TITLE
[BUG] Watchdog plugin constantly restarts application

### ISSUE THREAD

**Issue by grokbeer** [evilsocket/pwnagotchi#875]
**Describe the bug**
The watchdog plugin does a good job of detecting the blindbug issue but since it only restarts the pwnagotchi service the kernel log doesn't change and so it constantly detects the same bug and restarts the application over and over.
Does restarting the application actually fix this bug or is a reboot required?

**To Reproduce**
1. Enable the watchdog plugin.
2. Wait for 5 "brcmf_cfg80211_nexmon_set_channel.*?Set Channel failed" messages to appear in the kernel log in a 5-minute period.
3. Watch the pwnagotchi service restart continuously.

**Expected behavior**
The plugin should only restart the application once to fix the bug.

**Environment (please complete the following information):**
 - Pwnagotchi version: v1.5.3
 - OS version: Debian 10.3
 - Raspberry Pi Zero W

**Comment by LowSkillDeveloper** [comment]
The same problem. But also the problem is that sometimes he sees blindness where it does not exist. Often the AI Mode does not have time to load up but already restart is triggered.

**Comment by iiwwnnaa** [comment]
Same problem

**Comment by AceArd86** [comment]
I'm also having this same issue. It's in a boot loop
