### ISSUE TITLE
Encryption page not work.

### ISSUE THREAD

**Issue by savenko-egor** [evilsocket/pwnagotchi#879]
Hello!

I try use encryption with RPi Zero W. WiFi network with name DECRYPT-ME was started and I can connect, but page 192.168.0.10 not work. I run netstat -tunlp command via ssh and I not see any service on 80 port. Please specify how I can fix this problem?

Best regards.

**Comment by atm-infosec** [comment]
Unfortunately, I have the same problem.

**Comment by atm-infosec** [comment]
Hey, 

sorry, time was quiet short the last two days. I think I found the problem. /usr/bin/decryption-webserver has no executive permissions for owner. So if you simply execute:

chmod u+x /usr/bin/decryption-webserver 

it should instantly work.

**Comment by savenko-egor** [comment]
Good! All works fine. Thank you!
