### ISSUE TITLE
[BUG] GPS and SPI e-paper conflict

### ISSUE THREAD

**Issue by Hexalt** [evilsocket/pwnagotchi#902]
**Describe the bug**
I definitely seem to be running into conflict when using the screen and GPS together. No output on /dev/ttyS0 or /dev/serial0 when enabled SPI is enabled.

The 2.13inch e-Paper HAT requires SPI. If the screen is enabled and SPI is disabled then the Pwnagotchi service will fail to run and gps output is sent on /dev/ttyS0 or /dev/serial0.  Pwnagotchi service will load if screen is disabled.

**To Reproduce**
1. Connect e-paper and GPS to GPIO pins
2. Enable waveshare_2 display, SPI, and Serial Port hardware
3. Reboot
4. No GPS output on /dev/ttyS0 or /dev/serial0.

**Expected behavior**
Everything boots up. GPS output on /dev/ttyS0 or /dev/serial0.

**Environment (please complete the following information):**
 - Pwnagotchi version 1.5.3
 - Type of hardware
Raspberry Pi Zero WH
2.13inch e-Paper HAT
L76X GPS Module(16332)
PiSugar

**Additional context**
Reproduced on a new install of Pwnagotchi.

**Comment by ajaswa** [comment]
I have the same problem with a fresh install of Pwnagotchi.

Environment:

**Pwnagotchi version 1.5.3**
**Type of hardware**
Raspberry Pi Zero WH
2.13inch e-Paper HAT
Ublox GPS NEO-6M
UPS-Lite V1.2

I came across this post suggesting a solution to the issue: https://community.pwnagotchi.ai/t/serial-uart-not-working-on-gpio-14-and-gpio-15/306/6

I spent some time sorting though the code and finding where that header file is complied for pwnagotchi and swapped it out for the header file that does not tie up the uart gpio pins. Any feedback would be greatly appreciated.
