### ISSUE TITLE
[BUG] IPv4 traffic not working when using USB to ethernet adapter (eth0) over OTG. 

### ISSUE THREAD

**Issue by Tuinslak** [evilsocket/pwnagotchi#908]
**Describe the bug**

There's an issue where IPv4 traffic would not work when eth0 is connected (i.e. usb-ethernet adapter over OTG). The static route for usb0 precedes the DHCP route for eth0. Only IPv6 traffic would work, but not IPv4 until the metric for usb0 is increase and thus lowered in priority. If no eth0 is plugged in, internet works fine over usb0.

**To Reproduce**
1. plug in ethernet adapter 
2. wait for eth0 to get an IP
3. ping 1.1.1.1

**Expected behavior**
Ping works

**Screenshots**
n/a

**Environment (please complete the following information):**
 - Pwnagotchi version: 1.5.3
 - OS version: raspbian 10.4
 - Type of hardware: Pi zero W
 - Any additional hardware used: OTG cable and usb to ethernet adapter

**Additional context**
n/a

**Comment by rezzorix** [comment]
Try 

`systemctl disable dnsmasq
`
Then reboot

Worked for me on same version.
