### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by fennectech** [evilsocket/pwnagotchi#935]
**Describe the bug**
Pwnagotchi keeps restarting every few minutes   displatying the startup strings
**To Reproduce**
1. Turn it on
2. let it boot
3. sometimes it craashes 

**Expected behavior**
It should turn on and pwn

**Environment (please complete the following information):**
 - 1.5.3
 - default shipped with image
 - pi zero w
 - pisugar v1

**Additional context**
There is wierdness in the log.   
[pwnagotchi.log](https://github.com/evilsocket/pwnagotchi/files/5361815/pwnagotchi.log)

**Comment by fennectech** [comment]
Additionaly   I did a fsck on the ext4 partition and there were no issues.

**Comment by LowSkillDeveloper** [comment]
Have you turn on the watchdog plugin? If so, then turn it off.

**Comment by fennectech** [comment]
After clearing out a 5MB pwngrid log file it is working fine.  Sadly i dont have the files any more. So i cant recreate the issue.

**Comment by debian-user-france1** [comment]
please close the issue or unname it if you have the same issue again
