### ISSUE TITLE
sha256sum wrong

### ISSUE THREAD

**Issue by debian-user-france1** [evilsocket/pwnagotchi#943]
france1@ubuntu-desktop:~/Downloads$ sha256sum pwnagotchi-raspbian-lite-v1.5.3.zip 
116056931a1d2f56f28ec14e8431ae3b62bb27c8b7a9cdbf07423676804292ab  pwnagotchi-raspbian-lite-v1.5.3.zip
france1@ubuntu-desktop:~/Downloads$ cat pwnagotchi-raspbian-lite-v1.5.3.sha256 
46940952d63ebc739c6703c39145bc75007ec05bbccff69025b71d9687f71eb9  pwnagotchi-raspbian-lite-v1.5.3.img
france1@ubuntu-desktop:~/Downloads$ 

I downloaded the zip file twice

**Comment by debian-user-france1** [comment]
sorry, the line...

**Comment by debian-user-france1** [comment]
you first have to unzip the zip file and then checksum...

**Comment by sabotagebeats** [comment]
thanks this worked
