### ISSUE TITLE
[BUG]can't login via android-phone

### ISSUE THREAD

**Issue by keevinzha** [evilsocket/pwnagotchi#956]
**Describe the bug**
 have connected the pwnagotchi via bluetooth to my android phone, and the BT symbol has become C, when i try to login the 192.168.44.44:8080 with the passwd of pi user, I got passwd wrong and unauthorized

**To Reproduce**
1. visit 192.168.44.44:8080
2. input username and passwd
3. got wrong passwd

**Expected behavior**
login successfully with my phone

**Environment (please complete the following information):**
 - Pwnagotchi version v1.5.3
 - Android10
 - Huawei mate10

**Additional context**
I wonder which passwd should I use or where can I change this passwd?

**Comment by funkymonkey5150** [comment]
SSH into pi and then u are able to change the default password
