### ISSUE TITLE
Can't find default.toml

### ISSUE THREAD

**Issue by a95123hsu** [evilsocket/pwnagotchi#978]
I am new to pwnagotchi, and I know that I can change the config file. I am not sure is it suppose to save all my setting from config.doml into a default.doml, and remove my config.doml after the first boot. However, when try to find files by sd card, I couldn't find either config.doml or default.doml. 
I have try to create another config.doml and put it into the sd card, but it won't boot if I do that.
So I am confuse, where and how should I make changes for my config file?

**Comment by uwuforever** [comment]
It's 'config.**t**oml' not 'config.doml'. You should edit the file: `/etc/pwnagotchi/config.toml` if you want to update your configuration.

Don't edit default.toml - it will be overwritten.
