### ISSUE TITLE
What's going on?

### ISSUE THREAD

**Issue by swanserquack** [evilsocket/pwnagotchi#981]
## Context
I'm just trying to set up the pwnagotchi normally to use it for general testing purposes.

## Your Environment

- [Yes] You're using the official images

- [Yes] You're using a raspberry pi 0

- [No] You're using a supported LCD

My Raspberry Pi Zero W has been stuck on the same screen for a while (About 6 hours) and I have no idea what's wrong. I've connected it to an HDMI display and when everything is finished loading then the screen is just on the tty login screen and I don't know if it's a screen issue or something else. I'm just trying to get the thing set up and I've already tried reflashing it and when I attach it to my windows 10 laptop it shows up as a USB COM4 device and it doesn't show up anywhere else or does anything. The web UI is non-existant according to my laptop and pinging it shows nothing.
Thanks In Advance

**Comment by aspman** [comment]
Have you installed the rndis driver for Windows 10? Ethernet gadget is no longer plug and play since a Windows update last year.

**Comment by swanserquack** [comment]
> Have you installed the rndis driver for Windows 10? Ethernet gadget is no longer plug and play since a Windows update last year.

Sorry for the late response, I have now found the [correct driver](https://forum.moddevices.com/t/rndis-driver-for-windows-10/299/5) after searching for a few hours and following [these](https://community.pwnagotchi.ai/t/windows-10-connection-sharing-guide-thing-for-rpi0w-pwnagotchi-v-1-4-0-and-earlier/273) instructions to install the driver. I now have everything working but thanks for your concern.
