### ISSUE TITLE
[BUG] No connection to the internet

### ISSUE THREAD

**Issue by Luca-Hiller** [evilsocket/pwnagotchi#982]
Hey, I recently tried to connect the pwnagotchi to the Internet while I connected it to my Windows 10 PC and set up everything as described, but I still can't establish an Internet connection, but an SSH connection is possible The pwnagotchi is on the Version 1.5.3 would be very nice if someone can help

**Comment by evilsocket** [comment]
should be fixed with https://github.com/evilsocket/pwnagotchi/commit/298ed2400891c9893aa20aa869064b2ffc0b73b2
