### ISSUE TITLE
I can't run Pwnagotchi on my raspberry Pi4B 8GB.

### ISSUE THREAD

**Issue by kangjiayin** [evilsocket/pwnagotchi#988]
![图像](https://user-images.githubusercontent.com/67104974/114293518-634c9780-9ac9-11eb-82ae-e52330986a12.jpeg)

**Comment by kangjiayin** [comment]
I can use all the system such as ubuntu raspberrypios without pwnagotchi.

**Comment by lolzdatguy** [comment]
The image was not made for this board. Or at least that is my guess. You could install it manually, there is a guide for that on pwnagotchi.ai

**Comment by kangjiayin** [comment]
> The image was not made for this board. Or at least that is my guess. You could install it manually, there is a guide for that on pwnagotchi.ai

Thanks, I will check my step again.

**Comment by swanserquack** [comment]
> > The image was not made for this board. Or at least that is my guess. You could install it manually, there is a guide for that on pwnagotchi.ai
> 
> Thanks, I will check my step again.

I got the same issue. Followed all the steps. I think its a firmware issue so its out of our hands.

**Comment by kangjiayin** [comment]
> > > The image was not made for this board. Or at least that is my guess. You could install it manually, there is a guide for that on pwnagotchi.ai
> > 
> > 
> > Thanks, I will check my step again.
> 
> I got the same issue. Followed all the steps. I think it's a firmware issue so it is out of our hands.

Have you ever try to install it on Linux?

> > > The image was not made for this board. Or at least that is my guess. You could install it manually, there is a guide for that on pwnagotchi.ai
> > 
> > 
> > Thanks, I will check my step again.
> 
> I got the same issue. Followed all the steps. I think its a firmware issue so its out of our hands.

Have you ever try to install it on Linux?

**Comment by kangjiayin** [comment]
> > > The image was not made for this board. Or at least that is my guess. You could install it manually, there is a guide for that on pwnagotchi.ai
> > 
> > 
> > Thanks, I will check my step again.
> 
> I got the same issue. Followed all the steps. I think its a firmware issue so its out of our hands.

Have you ever try to install it on Linux?

**Comment by swanserquack** [comment]
> > > > The image was not made for this board. Or at least that is my guess. You could install it manually, there is a guide for that on pwnagotchi.ai
> > > 
> > > 
> > > Thanks, I will check my step again.
> > 
> > I got the same issue. Followed all the steps. I think its a firmware issue so its out of our hands.
> 
> Have you ever try to install it on Linux?

What do you mean by that?

**Comment by donut-donut** [comment]
works on a rpi 4 4gb just fine

**Comment by swanserquack** [comment]
> works on a rpi 4 4gb just fine

It's the RAM chip that's the problem. It happens when trying to install kali Linux as well. It's because the 8GB model has a different RAM chip and so it need new firmware and other things to make it work.

**Comment by kangjiayin** [comment]
> > works on a rpi 4 4gb just fine
> 
> It's the RAM chip that's the problem. It happens when trying to install kali Linux as well. It's because the 8GB model has a different RAM chip and so it need new firmware and other things to make it work.

Thx

**Comment by evilsocket** [comment]
the image is made for raspberry pi zero w boards, not this

**Comment by evilsocket** [comment]
https://pwnagotchi.ai/installation/#installing-on-any-gnu-linux

**Comment by kangjiayin** [comment]
> the image is made for raspberry pi zero w boards, not this

![截屏2021-04-25 上午12 17 46](https://user-images.githubusercontent.com/67104974/115965535-55345780-a55c-11eb-8905-35818b6d9ac3.png)

**Comment by evilsocket** [comment]
right, should. 

it's not officially built for Rpi3 and Rpi3 models and it should work on some of them, i don't test every hardware revision of other boards other than pi0w and it's likely that compatibility can break for newer ones. That is why I linked Linux generic instructions so that one can work with raspbian or whatever distro they have running on whatever board.

**Comment by kangjiayin** [comment]
> right, should.
> 
> it's not officially built for Rpi3 and Rpi3 models and it should work on some of them, i don't test every hardware revision of other boards other than pi0w and it's likely that compatibility can break for newer ones. That is why I linked Linux generic instructions so that one can work with raspbian or whatever distro they have running on whatever board.

Thank you.
best wishes.
